### ISSUE TITLE
Portable Ryujinx

### ISSUE THREAD

**Issue by ibex-are-goats** [Ryujinx/Ryujinx#1075]
I would like a way to keep all app files in the app directory. So no using the C:\Users\username\AppData\Roaming\Ryujinx folder.

**Comment by EmulationFanatic** [comment]
Another user asked for this today. 
![image](https://user-images.githubusercontent.com/62343878/84528450-f136d680-ac9c-11ea-813e-95fff20c0848.png)

**Comment by reloxx13** [comment]
i appreciate the work of ryu, but the missing possibility of changing the user folder is a killing feature.
i can live with graphic bugs and lags, but not with a filling and dieing system ssd.

**Comment by cooperate** [comment]
With the advent of local multiplayer this feature has become more important.  Titles like AC:NH could leverage local multiplayer on one PC if Ryujinx could run multiple portable instances.  Currently this is impossible because a shared directory for system configuration and user data means only 1 "Switch" per PC.

**Comment by reloxx13** [comment]
For future googlers

Create a shortcut with
`Ryujinx.exe -r <my-data-dir-path>`

Thx for this!

**Comment by rna0** [comment]
as much as i would love this feature, in the meantime, it is achievable to reference the dir with link shell extention
