### ISSUE TITLE
Implement a Disk Shader Cache

### ISSUE THREAD

**Issue by Ghostotakoi** [Ryujinx/Ryujinx#1542]
## Feature Request

Implement a Disk Shader Cache (Not in RAM)

#### Overview:
A Disk Shader Cache will greatly improve performance and decrease or eliminate the stutters after several runs. 

#### Smaller Details: 
I´m not a dev, so I can´t tell you guys how to do it.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
Will greatly improve performance and decrease or eliminate stutter. May also fix audio stutter caused by shaders compilation.

**Comment by jduncanator** [comment]
This is currently in development.

**Comment by shukenmg** [comment]
@jduncanator 
How is this coming along?

**Comment by jduncanator** [comment]
Hey @shukenmg. Sorry for the recent lack of updates, I’ve unfortunately had to take a break from the project the last couple of weeks due to some things happening in my personal life that need my full attention.

I’m hoping to be able to return in the coming week, and will be focusing all my time on getting shader cache PR’ed and into master!

Thanks for your patience!

**Comment by shukenmg** [comment]
@jduncanator Oh nice :) 
Looking forward to it 💯
