### ISSUE TITLE
My Ryujinx is slow

### ISSUE THREAD

**Issue by tampy9** [Ryujinx/Ryujinx#1706]
How do i fix this? I tried playing fire emblem and its super slow. Tried odyssey too and it runs like shit. I dont have this problem on yuzu btw. 

[Ryujinx_2020-11-13_17-58-29.log](https://github.com/Ryujinx/Ryujinx/files/5536486/Ryujinx_2020-11-13_17-58-29.log)

**Comment by BSoDGamingYT** [comment]
Disable the 60 FPS mod...

Because : 
1. You wont be able to get 60 at all times
2. The PPTC cache doesnt work when you use exefs mods (Resulting in lower than normal performance at boot)
3. FETH seems to have a game speed issue, where even when it says 30 FPS...the game appears to run slower than expected fullspeed

**Comment by tampy9** [comment]
Same performance even without the 60 fps mod. its unplayable for me. i have watched some vids on youtube and they seem to run it fine..

**Comment by BSoDGamingYT** [comment]
I guess play it on your switch for now and monitor the emulators progress for future performance upgrades

**Comment by AcK77** [comment]
This is for development issues. Please come to our Discord server for support, you can access that here: https://discord.gg/N2FmfVc.
