### ISSUE TITLE
Corrupted images on Animal Crossing New Horizons

### ISSUE THREAD

**Issue by Sbrockat** [Ryujinx/Ryujinx#1787]
In the home wardrobe or in the Able Sisters shop a lot of images are corrupted (picture below).

![ACNH_screen](https://user-images.githubusercontent.com/70136156/101335628-bee7e980-3879-11eb-99c9-f46414748660.PNG)

Environment

- Ryujinx version: 1.0.5942</br>
- Game version:  ACNH 1.6.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: ryzen5 3600
  - GPU: ATI rx570
  - RAM: 16GB

Thanks in advance for any help!

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/250

**Comment by Sbrockat** [comment]
Thanks for reply. This was an old post and most of issues have been solved. 
This is not the case of random items corruption but i have only that issue. Other items are correctly displayed.

**Comment by GamerzHell9137** [comment]
Game compatibility and issues are supposed to be posted in the Compatibility Github which is the linked one, not here.

And its already reported if you scroll a bit

"
There is a chance of random texture corruptions occuring. Examples of this are: Items rendering wrong icons, objects drawing weird flickering shadows (Video 1), objects rendering incorrectly (Screenshot 8), particle effects like falling leafs having wrong colors.
"

**Comment by jduncanator** [comment]
Thanks for the report @Sbrockat! We always appreciate getting reports and feedback from the community.

As @GamerzHell9137 eluded to, the best place for this feedback is on the bug for the game itself on our Game Compatibility tracker.

Feel free to leave your feedback there, for now, I’ll close the issue on this issue tracker, which is design more to track actionable bugs in the emulator, rather than specific bugs in games.

**Comment by Sbrockat** [comment]
Okay thanks. May i put the same post on the Game Compatibility Github?

**Comment by jduncanator** [comment]
@Sbrockat Sure can! Please do 👍
