### ISSUE TITLE
Ryujinxs "Automatically compiled builds" does not look like it was pre-complied for macOS.

### ISSUE THREAD

**Issue by TNT6161671** [Ryujinx/Ryujinx#1861]
Ryujinxs automatically compiled builds for macOS is just a .zip file.
When you extract it, its just a folder with wierd files (think its code/ui).

OS: macOS 10.13.6
Browser: Google Chrome

Please tell me if i did something wrong.

**Comment by EmulationFanatic** [comment]
Hi @TNT6161671 , the macoS build actually requires a couple of dependencies to first be installed via brew. However, more importantly, the macOS client is currently in a non-workable state due to Apple deprecating OpenGL and there not being a vulkan or metal backend at this time. Your best bet is to use boot camp to dual boot with Windows and use Ryujinx there.
