### ISSUE TITLE
Enhance portable mode

### ISSUE THREAD

**Issue by ElektroStudios** [Ryujinx/Ryujinx#1879]
## Feature Request

This is a (basic and must-have) feature request that I do supposing that **Ryujinx** still not implemented it (otherwise please let me know):

Please consider to implement portable mode, that is the **bis**, **games**, **sdcard** and the other directories and any other files must be read/written from root directory of **Ryujinx.exe**. 

I cannot think of a good, actual and active emulator that is not portable itself or that does not provide the user a functionality to make it portable, like **PCSX2**, **RPCS3**, **Dolphin**, **Cemu**, **Citra**, **Cxbx-R**, **Xemu*** (**Xemu**'s devs will implement it in a next release) and of course **Yuzu**, just to mention some of them.

Please take into account that a vast amount of users will need emulators to be portable, not to save settings in the user roaming folder like **Ryujinx** does :(

Just let the end user the chance to decide the default behavior of the software in this meaning.

One easy way for all users to set portable mode probably would be to let them create a "portable.txt" file in the root folder of **Ryujinx.exe**, and then **Ryujinx** should do the magic to recognize the installation as a portable mode. Or through an option in the emulator UI.

Just consider this feature request. Thanks in advance.

**Comment by gdkchan** [comment]
Sounds like this was already implemented on https://github.com/Ryujinx/Ryujinx/pull/1505
Is that what you are referring to?

**Comment by EmulationFanatic** [comment]
This feature exists already and allows custom data directories to be set anywhere except the ryujinx program folder (as the auto-updater purges the contents of the program directory automatically on each update it performs). See https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#portable-mode for a how-to.

**Comment by ElektroStudios** [comment]
Thanks for support, however the need to always run the program passing a command-line argument (**-r**) is a workaround but its far from being considered a friendly and real portable mode implementation, and the shortcut file workaround its just the same thing in other form. Using a shortcut would be viable only if a shortcut path could accept relative paths (such as ".\..\ryujinxdata) which is not the case (there is a trick to run explorer in the shortcut destination, but can't start the program with "-r" arg).

The spirit of portability is to be able to store the program and its configuration in the same directory, and be able run it as normally (by double-clicking in the exe file!) and that it does **not** break when the directory is moved to another destination. That is not possible to achieve using the workaround above since a FIXED directory will be needed using a shortcut / command-line arg, no matter if the Roaming directory or other dir, nothing changes with this.

Then, In there any chance devs can consider to reopen this request and extend and improve this functionality?.

**Comment by mageven** [comment]
The command line argument works with relative paths regardless of how it is used (shortcuts, command-line, scripts, launchers, etc...)
So, you can make a "portable" directory and call `Ryujinx.exe -r ".\portable"` and it'll work. You can move them around freely with no issues.
The guide showcasing the feature using a shortcut is only one way of achieving it. If you think a shortcut doesn't work just add a simple .cmd file.

Cannot comment on the ease-of-use and spirit of portability as they're pretty subjective.

**Comment by EmulationFanatic** [comment]
I've reopened the issue while we see if there's way to expand the end user options to enable/disable this mode, and determine a way to protect the root directory during auto-update processes.

**Comment by mageven** [comment]
>determine a way to protect the root directory during auto-update processes

Related issue: #1594

**Comment by julianxhokaxhiu** [comment]
Another issue I've found in portable mode is, that if you try to install the firmware while running ryujinx on a clean portable folder, that has been created on the first run with `-r` and has a correct `prod,keys` in the system folder, and attemping to install the firmware leads to a crash:
```log
00:00:00.026 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6283
00:00:01.160 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:01.160 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
00:00:01.160 |N| Application PrintSystemInfo: Total RAM: 16295 MB
00:00:01.162 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:01.162 |N| Application PrintSystemInfo: Custom Data Directory: .\user
00:00:48.625 |I| Application HandleInstallerDialog: Installing firmware 11.0.1
00:00:50.240 |E| GUI.FirmwareInstallerThread Application : Unhandled exception caught: System.ArgumentNullException: Path cannot be null. (Parameter 'path')
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\Content\ContentManager.cs:line 1010
   at Ryujinx.Ui.MainWindow.RefreshFirmwareLabel()
   at Ryujinx.Ui.MainWindow.<>c__DisplayClass83_0.<HandleInstallerDialog>b__0() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 989
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Not sure if anyone else has this issue before.

**Comment by ElektroStudios** [comment]
Any E.T.A for this portable mode feature?

**Comment by ctindell81** [comment]
I wanted to come here with some advice/tips, since I must have all of my emus in portable mode (OCD), I created a symlink to the userdata folder. It is dead simple and allows you to keep your data in a separate folder. On my F: drive. I have an "Emulators" directory. In said directory, all of my emus are nested inside their respective system's folders. ie: "..\Nintendo Switch\Ryujinx". Within the "Ryujinx" folder, I have 4 directories, "Ryujinx Standard", "Ryujinx Online (LDN)", Ryujinx UserData", "Help/Archives" (the last contains tools, notes, full webpages and tutorials that I've saved reference later as well as archiving older versions of Ryujinx (for obvious reasons)

Not to lose focus of what I came here to help others with, I will explain a few key and (very) important things to keep in mind when symlinking a directory to the less tech savvy emu enthusiasts as well as giving a step-by-step in using the tool I am recommending called "SymlinkCreator", found on SourceForge. Just google it, it is the first hit in your search results. There are other ways to symlink a directory(including using command prompt), however I find that this app is quite easy and straightforward to use. 

Read everything before proceeding. A symlink is basically a sophisticated shortcut to either a folder or file that tricks programs into thinking they're using their default directory in the default location. I know it looks like a lot of work, but it only takes mere minutes to do this, I just am being as thorough as possible. I may be explaining what many users may know, but want this to be understood by a 5 year old (ok, not a 5y/o but the not so savvy user). 

I am not responsible for data loss, you spontaneously combusting, head exploding or your dog throwing up in your living room while eating supper. This comes as-is with no warranty or extra support(google knows a lot more than me), my instructions are a viable alternative to the method recommended here (which is just as viable) and will help you in accomplishing what you want if you follow these instructions to a "t".

Preparatory work:
NOTE: when you symlink, you must backup your original Ryujinx data folder, else resulting in DATA LOSS!!!
-Start Ryujinx, click File>Open Ryujinx Folder.
-When the window opens, press Alt+arrow up to go up one level, you will see the "Ryujinx" folder highlighted.
-IMPORTANT!!!!! YOU MUST RENAME SAID FOLDER TO "Ryujinx_old" (not doing this will result in data loss).
-After doing that, you need to create a new "Ryujinx" directory by pressing ctrl+shift+n and name it "Ryujinx".
-Next, you need to go to the location you want to actually keep your data , creating new folder outside of the Ryujinx emu directory. I have it titled "Ryujinx_UserData".

Creating your symlink:
-Run SymlinkCreator as admin.
-In the drop-down box, pick "Directory Symbolic Link".
-In the 'Destination (link)' field, this is where you browse to and select the new "..\AppData\Roaming\Ryujinx" (the empty "Ryujinx" folder you created alongside "Ryujinx_old") This is the directory you want the files moved FROM. Make sure you DO NOT select "Ryujinx_old".
-In the 'Source (target)' field, this is the location you need the files moved TO. ie:  "Ryujinx_UserData" (alongside your emulator folder, NOT INSIDE).
-Click "Create Link".

Final steps:
NOTE: Before you are finished, you still need to move all of the AppData from the "Ryujinx_old" directory.
-Go into said directory and press ctrl+a to highlight everything, press ctrl+x to cut, then go into the (empty) Ryujinx folder and press ctrl+v to paste the files into said directory. Alternatively you can go to the "Ryujinx_UserData" folder and paste them in there as well. This is where they are being store, afterall.
-Profit from not needing to launch Ryujinx with a special shortcut or bat file. 

Final Note: If you ever do a fresh install of Windows or create another account on your machine, you will need to do this again as symlinks are not permanently persistent. Furthermore, this is handy for other instances where you cannot change a program's cache or user data's directory. ie: Steam's "cache\downloads" folder, pre installation. You can even have multiple directories across multiple drives symlinking to a central folder. Symlinking removes many constraints caused by limited HDD space, unwanted SSD writing or wanting more control than a program allows. Hope this helps.

**Comment by kashinoda** [comment]
When using Ryujinx in portable mode it's not possible to install firmware, as @julianxhokaxhiu 
 highlights here: https://github.com/Ryujinx/Ryujinx/issues/1879#issuecomment-757577331

However you can create a BATCH file which launches the emulator and changes the Windows variables for AppData locations. Simply make a folder named 'data' in the same directory as your BATCH file, the emulator goes in the 'app' folder:

```
REM -- Path to the directory of this script (make sure to remove ending slash)
set CURRENT_DIR=%~dp0
REM -- Great example from Strawberry Perl's portable shell launcher:
if not "" == "%CURRENT_DIR%" if #%CURRENT_DIR:~-1%# == #\# set CURRENT_DIR=%CURRENT_DIR:~0,-1%

REM -- OVERRIDE the user environment variable to point to a portable directory
set USERPROFILE=%CURRENT_DIR%\Data

REM -- (Optional) Some programs do not use these environment variables
::set APPDATA=%CURRENT_DIR%\Data\AppData\Roaming>nul
::set ALLUSERSPROFILE=%CURRENT_DIR%\Data\AppData\Roaming>nul
::set PROGRAMDATA=%CURRENT_DIR%\Data\AppData\Roaming>nul

REM -- Start the application
start "" /D"%CURRENT_DIR%\app" "Ryujinx.exe"
```
For reference: https://superuser.com/questions/1226025/how-to-redirect-appdata-roaming-to-a-subdirectory-to-make-an-application-more

If you also want to include your game folder, edit your **LDNConfig.json** or **Config.json** file and use a relative path like so:

```
  "game_dirs": [
    "..\\switchgames"
  ],
```

Everything is now contained within a single folder, no more issues for me:
https://i.imgur.com/Ldn2Yef.png

**Comment by Psychotopia** [comment]
just lost all my game save assuming ryujinx was selfcontained and portable by default had it installed on a ssd for games windows 10 bricked it self as it does and wiped out the saves on resetting ryujinx not being portable by default is a bug in my eyes and honestly its the first emulator ive used that isnt very dissapointed

**Comment by EmulationFanatic** [comment]
> just lost all my game save assuming ryujinx was selfcontained and portable by default had it installed on a ssd for games windows 10 bricked it self as it does and wiped out the saves on resetting ryujinx not being portable by default is a bug in my eyes and honestly its the first emulator ive used that isnt very dissapointed

That is an unfortunate turn of events. Portable mode not being included by default is not a bug, however. The majority of programs today use the user's profile directories to store their operational data.

You can improve your overall computing experience by following these tenets:
1. Always keep backups of your data.
2. RTFM

**Comment by Psychotopia** [comment]
it would be eaiser to keep backups if the saves were say in the folder and not in a random app data folder and "the majority of programs" well thats a fun one most games keep there saves in documents my games a folder which funnily enough windows does not wipe on a reinstall and can be rerouted to a secondary hard drive for an additional level of protection

also most programs is not most emulators

and additionaly the majority of programs doing it does not make it better 

i honestly dont know why you would defend such a poor place to keep save game data

**Comment by EmulationFanatic** [comment]
You had the option of moving the data directory via a number of methods. Your complaint is noted, however just because you failed to read any documentation on the program or ask for support before catastrophe hit doesn't mean we're evil overlords laughing at your misfortune.

**Comment by Psychotopia** [comment]
theres so many things wrong with your last response 
1. "ask for support before catastrophe hit" im not going to ask for support on a hypothetical windows brick in advanced for every game or program i use that would be insane

2."doesn't mean we're evil overlords laughing at your misfortune." at no point have i implied you were laughing at me or that you we're and evil overlord. nor have i thought these things. as a developer of an open source public emulator that will bring joy to thousands of people i think of you more as charitable philanthropists spending time instead of money

3."however just because you failed to read any documentation on the program"  there is no link to the documentation within the program the help button has credits and updates neither of which link to the wiki or any help articles.  above kashinoda shows that to get it working you need to go to a completely outside source unrelated to ryujinx to find the infomation needed to make the function work properly. also on the main website "https://ryujinx.org/" there is no obvious link to the wiki or documentation *i cant find **any** but id hope you have one there*  in the process of using ryujnix website to download to extract to running the only link to documentation is the first launch before you add the prod which no help if you add the portable mode and its documentation after i first installed it . 

4."You had the option of moving the data directory via a number of methods." non of which work from within the program or are self evident there isnt even an option to change save location in the settings menu which i consider an oversight especialy considering you have the add game directory menu

5."you failed to read any documentation" how on earth would i have save files to lose if i didnt read any of the documentation without reading the documentation i wouldnt have even gotten to any games start screen let alone have added dlc and updates

also your program dosnt show up in the installed list nor does it have an installer it in fact works in a portable mode with the down side of saving files to your app data

this also means ryujinx leaves fingerprints and leftover data if you delete it bloating app data with extra files that might never be deleted due to a lack of uninstaller

**Comment by EmulationFanatic** [comment]
I'm sorry that you feel this is an argument or debate and need to attack my responses. I'll circle back to my suggestions earlier regarding reading the documentation: the very first time you launch the emulator it prompts you to install keys. Therein this window pops up. 

![image](https://user-images.githubusercontent.com/62343878/120515010-18455700-c38b-11eb-9660-dbd03afd9bd5.png)

The setup guide has had instructions on portable mode since it was added nearly a year ago, with steady updates since then. Best of luck and I hope you run into fewer Windows issues.
