### ISSUE TITLE
Is it possible to add an option to disable anti-aliasing? 

### ISSUE THREAD

**Issue by JIuBeP** [Ryujinx/Ryujinx#2032]
Is it possible to add an option to disable anti-aliasing? (remove the soap and increase the productivity a bit)

**Comment by CeruleanSky** [comment]
This feature was previously requested and the rational for denying it was listed here: https://github.com/Ryujinx/Ryujinx/issues/584

A mod would likely be the best route, look to game hacking forums to see if any exists, request one, or make your own.

**Comment by riperiperi** [comment]
Modern game rendering pipelines (e.g. deferred lighting) generally do not support MSAA, which is why you see basically all games using temporal AA or some other technique these days. If we were to allow forcing MSAA, then it would work with a disappointingly low number of games. Temporal AA isn't an option for us either, as it requires that the game supply motion vectors per pixel, and we'd need to know where to find that info to apply it, so our only option would be something that works on a single image like FXAA.

Generally, the better option is to attempt to render at a higher resolution, then supersample that higher res image down to the output resolution, which ryu does support. Currently this works up to 2x the output resolution, but I want to implement a technique that works with much larger images too.

**Comment by riperiperi** [comment]
Sorry, I didn't realize you were asking for "disabling" anti-aliasing. Unfortunately, as I described games are now using shader techniques for anti aliasing such as temporal anti aliasing and FXAA, which are implemented using general purpose shaders. As "general purpose" implies, these shaders can really do anything so we can't exactly detect when a shader is "meant" to do anti aliasing and modify it. Determining shader intent would probably be a crazy project in itself, and not one I think you'd come out with good results to.

Your best hope for disabling graphical features is modding the original game. Such mods exist for games like the Xenoblades.

**Comment by stizzo1** [comment]
If correct, generally, for games, the handheld mode (720p) results without aa technique (example AstralChain)

In my case I use the custom resolution 2x (1440p), but to match the docked mode, you can set the res 1.5 (1080p in handheld mode) and if necessary, use the ReShade with FXAA filter, if you have a good video card (in my case an RTX Nvidia)

**Comment by EmulationFanatic** [comment]
To sum up...this is not possible.
