### ISSUE TITLE
[Feature Request] Cache installed games list

### ISSUE THREAD

**Issue by moon-chilled** [Ryujinx/Ryujinx#2084]
My game ROMs are on a slightly slow NAS, so it usually takes a few minutes for the games list to populate.  It would be nice if that list could be cached (maybe key with filenames+mtimes).

**Comment by AcK77** [comment]
There is already a cache which store metadata (and more) informations, but Ryujinx have to check if files still exists when you started it. That’s why it takes some minutes to populate the games list with your slow NAS.
I close the issue since it’s not a Ryujinx issue.
In case I’ve misunderstood something don’t hesitate to give us more informations and we will reopen it if needed.

**Comment by cleverestx** [comment]
My NAS is a DS1621+ and is on a 10GB Ethernet (local) connection. It is NOT a 'slow NAS' and it still takes minutes (too long) to load up 309 games each time it initially opens the game list/application. Playing and loading games are fine.
