### ISSUE TITLE
Can't launch any game on latest Windows build

### ISSUE THREAD

**Issue by arnoldsecret** [Ryujinx/Ryujinx#2232]
## Bug Report

As of 1.0.6845, Ryujinx refuses to launch any game.

### What's the issue you encountered?

As observed by the logs while starting up any game,
`00:00:01.058 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.`

### How can the issue be reproduced?

Launch any game on the latest Windows build.

### Log file

[Ryujinx_1.0.6845_2021-04-21_09-11-20.log](https://github.com/Ryujinx/Ryujinx/files/6347422/Ryujinx_1.0.6845_2021-04-21_09-11-20.log)

### Environment?

- Ryujinx version: 1.0.6845
- System Specs:
  - OS: Windows 10 Pro 64-bit
  - CPU: i7-4500U
  - GPU: NVIDIA GeForce GT 740M
  - RAM: 8GB
- Applied Mods : No

### Additional context?

Every game that I have, (Blaster Master Zero 1&2, Iconoclasts, METAGAL, Pikuniku) all throws up the same error message. I even tested this on a new Ryujinx install. I'm using portable mode for both of these tests.

**Comment by EmulationFanatic** [comment]
The emulator is working fine here on version 1.0.6845. I've tried with and without portable mode, and clean install vs. my existing configuration. The games launched every time

**Comment by CeruleanSky** [comment]
These will likely not work since this is a shot in the dark, but since you are stuck can't hurt:
* Try removing all the games but one
* I know you did a fresh install, but how long are the paths, maybe extract ryujinx to X:\Ryujinx and perhaps your games to X:\RyuGames and start over with that.
* Are your locale/language settings and your switch's firmware's locale non-english and if so what is it, also are there any international characters in the file names or in your install?
* do a `dir /s /b > filestructure.txt` with a command prompt 
  or with powershell `Get-ChildItem -Recurse | Select-Object -ExpandProperty Fullname | Out-File filestructure.txt`  
  inside your portable folder, your settings folder and your games folder and post those here, be sure to verify the files to ensure there is no sensitive information.

**Comment by arnoldsecret** [comment]
[filestructure.txt](https://github.com/Ryujinx/Ryujinx/files/6349174/filestructure.txt)

**Comment by AcK77** [comment]
Your portable folder seems to have Ryujinx files missing. 
- What if you try to download it again and try again?
- What if you run Ryujinx is normal mode (not the portable one)?

**Comment by arnoldsecret** [comment]
I downloaded a clean install, and it still doesn't work. Running it in normal mode works up until it crashes to desktop.
[Ryujinx_1.0.6850_2021-04-26_09-22-02.log](https://github.com/Ryujinx/Ryujinx/files/6373654/Ryujinx_1.0.6850_2021-04-26_09-22-02.log)

**Comment by AcK77** [comment]
The current issue is something else Related to your gpu, I suggest you to come at our discord (https://discord.gg/ryujinx) for support since it seems to be an issue at your end. Thanks.
