### ISSUE TITLE
Xenoblade Chronicles 2 memory leak

### ISSUE THREAD

**Issue by ivfranco** [Ryujinx/Ryujinx#2344]
### What's the issue you encountered?

Once into a big map, while walking around the Ryujinx.exe process will slowly but steadily exhaust vram then main memory, possibly resulting in crash of the emulator process and sometimes the entire desktop environment. After the memory leak the emulator cannot be shut down normally. </br>
No change is made to the emulator or its settings. </br>

### How can the issue be reproduced?

The memory leak will not happen until Gormott Province Upper Level, the first big map of the game. Once there, walking around, looking around or entering battle could trigger the leak. Having more member in the party seems to worsen the case, the game never crashes this way with a single character in the party.

### Log file

[Ryujinx_1.0.6906_2021-06-04_21-58-36.log](https://github.com/Ryujinx/Ryujinx/files/6599328/Ryujinx_1.0.6906_2021-06-04_21-58-36.log)
The emulator is forcefully terminated.

### Environment?

- Ryujinx version: 1.0.6906</br>
- Game version: both the NA version (0100e95004038000) 2.1.0 and the Japanese version (0100f3400332c000) 2.0.2.</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3600
  - GPU: NVIDIA Geforce 1660 super
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Whenever the memory leak happens the amount of memory occupied by Ryujinx.exe reported by task manager and resource monitor diverge. The number reported by task manager usually caps at ~4GB but the number reported by resource monitor will grow unbounded.

**Comment by kqwyf** [comment]
I also noticed that while the task manager reports that Ryujinx has taken ~4GB memory, quitting Ryujinx causes a ~10GB drop on the memory usage (also reported by the task manager).

**Comment by Benedani** [comment]
> I also noticed that while the task manager reports that Ryujinx has taken ~4GB memory, quitting Ryujinx causes a ~10GB drop on the memory usage (also reported by the task manager) when playing XC2.

That one is a certified Windows moment. Task manager doesn't show you how much memory a process actually uses up. Just noting this; this information *could* help track down the leak however.

**Comment by kqwyf** [comment]
I'm here to provide a bit more findings (maybe unrelated).

Recently I upgraded my NVIDIA driver to Game Ready 466.63, and found XC2 to crash much more frequently. By looking at the memory usage reported by the task manager, I believe it was caused by OOM. However, after I downgraded my driver to 466.27, things work fine. Now when the memory usage raises to a high level, the fps drops for a while and the memory usage becomes smaller. It seems that some GC has been done. This is **not** observed on the newest driver.

My graphics card is GeForce GTX 1660Ti, if anyone wonders.
