### ISSUE TITLE
Consider using DSA functions on OpenGL

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#2508]
#### Overview:
OpenGL 4.5 introduced support for DSA functions. Basically, they allow the state of the OpenGL objects to be changed without needing to bind them beforehand. On older versions of OpenGL, the typical way to copy data from one buffer to another for example, is:
```cs
GL.BindBuffer(BufferTarget.CopyReadBuffer, sourceBufferHandle);
GL.BindBuffer(BufferTarget.CopyWriteBuffer, destinationBufferHandle);

GL.CopyBufferSubData(BufferTarget.CopyReadBuffer, BufferTarget.CopyWriteBuffer, srcOffset, dstOffset, size);
```
Using the equivalent [DSA function](https://www.khronos.org/opengl/wiki/Direct_State_Access) here, we can reduce the number of calls required:
```cs
GL.CopyNamedBufferSubData(sourceBufferHandle, destinationBufferHandle, srcOffset, dstOffset, size);
```
Reducing the number of calls can bring a small performance improvements on games that does a large number of binding/buffer copy/texture copy/upload etc operations.

One thing to note too, is that it binds texture at binding point 0 before each draw/dispatch:
https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Graphics.OpenGL/Pipeline.cs#L1229
This is done because binding the texture to modify its state would also replace the texture previously bound at 0. With DSA this is no longer a problem as the texture handle is passed directly, without binding, so this can be removed.

The reason the new functions are not used right now, is because we used to target OpenGL 4.3, and older drivers that does not support DSA. Nowadays though, we require OpenGL 4.5, so it shouldn't be an issue anymore.

#### Nature of Request:  
Code and performance improvement. Passing the handles directly instead of binding them is also less error prone, as its not possible to leave things bound and later have their state unintentionally changed.

### Why would this feature be useful?
Makes the code more clear and faster.

**Comment by ReinUsesLisp** [comment]
A few things to have in mind when transitioning into DSA:
- `CreateFramebuffers` is broken on Nvidia. It will create an [EXT_framebuffer_object](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_framebuffer_object.txt) instead of a core framebuffer. These can't have attachments with mismatching sizes. A workaround is to call `GenFramebuffers` + `BindFramebuffer(READ_FRAMEBUFFER, fbo)`.
- DSA gives less information about the buffer usage to some drivers. For example, if a mutable buffer is created on mesa with DSA and used as a readback PBO, it may be put on video memory rather than host cached memory on mesa (see [this](https://gitlab.freedesktop.org/pepp/mesa/-/blob/master/src/mesa/state_tracker/st_cb_bufferobjects.c#L248-251)), killing readback performance.
- DSA can be slower when the same handle is used contiguously (e.g. lots of `ProgramUniform1i` vs. `Uniform1i` where the program handle is only resolved on UseProgram). Although this shouldn't affect Ryu.
- There used to be some bugs on Intel related to VAOs, no idea if they still happen.

That said, I think DSA is much better than having to deal with state leaks related to object bindings.

About OpenGL 4.5 being required, there's also [EXT_direct_state_access](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_direct_state_access.txt) that's more widely supported on Windows, but only supported on somewhat recent mesa versions. Just mentioning it, in case OpenGL 4.4 Intel GPUs want to be supported in the future.

**Comment by mpnico** [comment]
Can I take a look at this ? Thank you.

**Comment by gdkchan** [comment]
I will close this one, we had an attempt to implement this that did not show performance improvements, and also hit bugs with some drivers, which meant we couldn't use DSA for everything. Also Vulkan is pretty much our main API now and likely where most of the effort will be spent going forward, so I don't think it's worth doing it anymore.
