### ISSUE TITLE
Ryujinx Black Screen w/ Audio, LDN Build

### ISSUE THREAD

**Issue by RelBeingWeird** [Ryujinx/Ryujinx#2682]
### What's the issue you encountered?
I followed [this video](https://youtu.be/EqkW61NjDpU) and installed Ryujinx to play Animal Crossing: New Horizons and set up everything as the video said.
In the master build of Ryujinx, the game had worked fine and was running well. However, in the LDN build, despite no settings being changed from the master build, it showed nothing but a black screen and after a while, the main menu theme song begun to play. I pressed the 'A' button to continue to start the game despite not having visual, and the game starting sound played.
It's notable that I did not mod or modify the Ryujinx files, only settings I changed in options were in both builds:
- V-Sync OFF
- Timezone
- Audio Backend OpenAL 
I am using the latest MASTER build of Ryujinx as of this post, and the official LDN build release from patreon.

### How can the issue be reproduced?
1. Follow the video above.
2. Launch Animal Crossing: New Horizons with the latest update and firmware 13.0.0

### Log file
https://pastebin.pl/view/38f62543

### Environment?

- Ryujinx version: 
MASTER BUILD: 1.0.7047
LDN BUILD: 1.0.0-ldn2.3
- Game version: 1.11.1
- System Specs:
  - OS: Windows 10
  - CPU: Intel Core i5-9400F
  - GPU: AMD Radeon Rx 580
  - RAM: 16GB
- Applied Mods : No

### Additional context?
I applied a 60FPS Mod in the master build while setting it up as I always do in Yuzu, but the mod was running too fast and made Ryujinx crash so I deleted it. The game still proceeded to run extremely fast after deleting it, however. Should not have a relation to the LDN build as it was only in the master build, but notable.

**Comment by RelBeingWeird** [comment]
My AMD drivers are up-to-date.

**Comment by EliEron** [comment]
The LDN build is quite old at this point (~4 months old) and a lot of changes have happened in those four months. When AMD released driver version 21.4.1 of their Windows driver it completely broke rendering on Ryujinx. The issue was fixed in this PR (#2323) but since it was merged after the release of LDN it is not included in it.

If you revert to a driver older than 21.4.1 then LDN should start rendering again. But to be honest Ryujinx did not work great on AMD cards using the Windows driver back then, even when rendering was not broken. The Vulkan backend that is currently in development (#2518) massively improves performance and stability on AMD cards, and it is partly because this is in development that LDN has not been updated for a while. As the next version of LDN will hopefully ship with Vulkan support.

**Comment by RelBeingWeird** [comment]
So the only solution for this thus far is reverting to an older version of the drivers?

**Comment by CrusadingNinja** [comment]
> So the only solution for this thus far is reverting to an older version of the drivers?

Yes
