### ISSUE TITLE
Unable to access Chocobo GP race once character is select and you press Ready.

### ISSUE THREAD

**Issue by jvhellraiser** [Ryujinx/Ryujinx#3189]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[ I am unable to access chocobo GP when you access the character selection screen and you click ready you never go anywhere]</br>
[ I haven't make any changes at all in Ryujinx? ]</br>
[ N/A ]

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ i am not sure why  but no logs have been create since the issue is not something that make Ryujinx crash. ]</br>
[N/A. ]

### Environment?

- Ryujinx version: 1.1.65</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: Version 1.0.3</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(Windows 11)*
  - CPU: *(i7-9700k)*
  - GPU: *(e.g. NVIDIA RTX 2060)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ No ]

### Additional context?
![Screenshot 2022-03-11 195016](https://user-images.githubusercontent.com/16488761/157994059-a41c3779-52d7-4d9b-8b1e-86c1365cfc13.png)
![Screenshot 2022-03-11 195133](https://user-images.githubusercontent.com/16488761/157994066-ebc36317-bda8-4005-b39e-b0c7abfed412.png)

**Comment by EliEron** [comment]
Your issue report is quite confusing, your screenshots shows the game crashing on boot, but your description talks about being unable to enter the Chocobo GP race feature, which is an entirely different issue. I'm going to assume you manager to resolve the crashing issue and just address the one you actually describe in your report.

The Chocobo GP race feature is an online exclusive mode. Most online gameplay features do not work in Ryujinx due to them usually requiring a Nintendo account and access to Nintendo servers, which Ryujinx is unlikely to ever support.

The game has plenty of offline features you can enjoy on the emulator, but that specific race type will not work.

**Comment by jvhellraiser** [comment]
Sorry but i hear that there is an exclusive Offline Chocobo GP just like in Mario Kart & the story mode so one of them is giving error the error in the photos do appear but it wont crash Ryujinx at all you just click ok and the game will continue
loading normally, not sure why is that error appear.
