### ISSUE TITLE
Add a shortcut to start the game

### ISSUE THREAD

**Issue by Sev73n** [Ryujinx/Ryujinx#3250]
like rpcs3

 can launch the game with one click through shortcuts

This is useful for organizing our game library
![image](https://user-images.githubusercontent.com/16495885/161372277-3fd4d103-6e96-4712-8605-699feb1beffd.png)

**Comment by Wallduckie** [comment]
You are able to add your games to the main menu, to play them with one click. 
https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#adding-your-games-to-ryujinx
Check the Adding your Games section to see how to do so.

**Comment by Sev73n** [comment]
> You are able to add your games to the main menu, to play them with one click. https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#adding-your-games-to-ryujinx Check the Adding your Games section to see how to do so.

Is it possible to generate a shortcut to the desktop with the game icon, so that the game can be run  emulator automatically when I click to start ?

**Comment by MutantAura** [comment]
You can already use command line or terminal arguments to start game with Ryujinx or you can simply assign NSP and XCI files to start with Ryujinx like so:

![image](https://user-images.githubusercontent.com/44103205/162637355-a40d911e-c8e1-437d-a1de-f9c0b96b6347.png)

Then simply create a shortcut to that NSP or XCI. Any updates or DLC configured via the GUI will also be loaded like this. Frontends can make use of command line launch or via the headless builds.

**Comment by gdkchan** [comment]
Creating a shortcut that will launch the game automatically from the GUI is a valid feature request imo.

**Comment by MutantAura** [comment]
Maybe I misunderstand what the feature request is? We already support launching games via the GUI when they've been added, support creating a shortcut directly to the NSP or XCI and support frontend launch via terminal arguments.

**Comment by piplup55** [comment]
> Maybe I misunderstand what the feature request is? We already support launching games via the GUI when they've been added, support creating a shortcut directly to the NSP or XCI and support frontend launch via terminal arguments.

a button to create a shortcut i would think

**Comment by MutantAura** [comment]
Re-opening. Although I think making it clearer in the request if this is the desired feature?

> a button to create a shortcut i would think

**Comment by gdkchan** [comment]
> Re-opening. Although I think making it clearer in the request if this is the desired feature?
> 
> > a button to create a shortcut i would think

Right, the issue description should be updated, because what was requested on the main post and on the second comment made by the author (https://github.com/Ryujinx/Ryujinx/issues/3250#issuecomment-1086964374) are different requests. The one on the main post right now doesn't make sense as it's something we already have.

**Comment by NitroTears** [comment]
From what I can see, you are already able to directly 'launch' a game by passing the path to the .XCI (for example). 
On windows I ran `C:\Users\Nitro\Desktop\Ryujinx>Ryujinx "E:\BAK\ASTRAL CHAIN.xci" --fullscreen` And this practically acomplished the shortcut function completely. 

The arg for the path to file could be changed to a specific argument instead of the default case in this switch:
https://github.com/Ryujinx/Ryujinx/blob/7ca779a26d76a3ad1edd94ba6c1cfd7466d73314/Ryujinx.Ui.Common/Helper/CommandLineState.cs#L73-L81

Assuming this doesn't become a much larger job then I anticipated, I'd be happy to pick up this issue. I assume we'd just add this to the right click menu on a game in the list.

I do also want to note that there is large wait between the short cut being click and the game starting, as the shaders are being loaded before the game starts.

**Comment by VanessaAfton** [comment]
> You are able to add your games to the main menu, to play them with one click. https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#adding-your-games-to-ryujinx Check the Adding your Games section to see how to do so.

Not helpful bro.. all the section teaches is adding the game's directory.. he said to make a shortcut to game
