### ISSUE TITLE
Any plan to publish a xbox uwp  version?

### ISSUE THREAD

**Issue by LGinC** [Ryujinx/Ryujinx#3308]
It so exciting to play ns game in xss/xsx.

**Comment by MutantAura** [comment]
- UWP is limited to a maximum of 2GB files (most switch ROMS are larger than this)
- Depending on how it was published Ryujinx may only have access to 2-4 CPU cores and 45% of the GPU.
- DirectX12 or DX11 are required as APIs. Neither of these are particularly suited to modern switch emulation and are not of much interest for developers.

This page is for the Xbox One's UWP restrictions but XBX/S have similar/identical limitations: https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/system-resource-allocation

**Comment by danprice142** [comment]
UWP is not that limited at all, Aethersx2 and RetroArch UWP can load files in excess of 8gb at least (I’ve tried)  from both the internal console memory and external NTFS drives, both in Dev Mode and Retail Mode.

If the UWP is set as a Game instead of a App it can use all cores and GPU but i think must have certain dependencies too.

DirectX12 is all that’s missing but there are these layers being worked on by Mesa and Microsoft to bring OpenGL and Vulcan to directx12 

glon12 supports OpenGL 4.2 with 4.3 support coming
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14881

dozen: Vulkan on D3D12 is also available
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14766

These layers do not currently work on UWP but could maybe work with Windows App APK
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/

**Comment by LeVraiRoiDHyrule** [comment]
> UWP is not that limited at all, Aethersx2 and RetroArch UWP can load files in excess of 8gb at least (I’ve tried) from both the internal console memory and external NTFS drives, both in Dev Mode and Retail Mode.
> 
> If the UWP is set as a Game instead of a App it can use all cores and GPU but i think must have certain dependencies too.
> 
> DirectX12 is all that’s missing but there are these layers being worked on by Mesa and Microsoft to bring OpenGL and Vulcan to DirectX12 so this could be something to keep a eye on
> 
> glon12 supports OpenGL 4.2 with 4.3 support coming https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14881
> 
> dozen: Vulkan on D3D12 is also available https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14766
> 
> These layers do not currently work on UWP but could maybe work with Windows App SDK https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/

Very interesting data, I can confirm that most limitations are gone if an UWP app is deployed as a Game and not an App (tried in Dev mode). Hope those Vulkan projects for D3D12 will grow, it would be so exciting to have switch emulation on XSX. What is done here is very interesting too : https://github.com/SirMangler/dolphin. Even if I fully understand that this is not at all a priority for switch emulators, that would be awesome.

**Comment by jduncanator** [comment]
The bigger issue is memory. UWP "Games" are limited to 5GB total allocations, shared across both CPU and GPU. Even for lightweight games, this would be a challenge to pull off with Ryujinx at the moment.
