### ISSUE TITLE
AMD Mario Kart 8 Deluxe Vulkan Lights Bug

### ISSUE THREAD

**Issue by rgbarros120** [Ryujinx/Ryujinx#3512]
Mario Kart 8 deluxe has a vulkan AMD light bug that needs to be fixed immediately.

My Specs: RADEON RX 560 OC 4G; RYZEN 5 1600; 16GB DE RAM (2400mhz)

![Sem título](https://user-images.githubusercontent.com/73244003/182047503-b63393dd-8956-4164-9765-9e0101370076.png)
[Ryujinx_1.1.200_2022-07-31_19-16-31.log](https://github.com/Ryujinx/Ryujinx/files/9229814/Ryujinx_1.1.200_2022-07-31_19-16-31.log)

**Comment by Leischii** [comment]
A friend of mine with an RX 580 has the same bug. On the second map of the first cup the bug is temporarily gone in the parts were you drive through the water. Not sure if that helps, but that was the only time when it didnt happen, so I thought it's worth pointing out. 
The ground was also glowing bright in some areas. Smooth and reflecting surfaces seemed to be the ones mainly doing that.

**Comment by Leischii** [comment]
The friend I mentioned in the last message told me that this bug seems to be fixed.

**Comment by MutantAura** [comment]
The new LDN build has a workaround to _somewhat_ mitigate this. It isn't actually fixed yet.

**Comment by MetrosexualGarbodor** [comment]
Please report game-specific issues in the [compatibility entry for the game](https://github.com/Ryujinx/Ryujinx-Games-List/issues/244). Thank you.

**Comment by AspaceZ** [comment]
i still have that issue,is there some setting i should change？

**Comment by ubise** [comment]
Is there any solution or progress about this issue? Because it's still happening to me.

**Comment by gdkchan** [comment]
Does the issue happen with the build at https://github.com/Ryujinx/Ryujinx/pull/4364#issuecomment-1416484126 ?
