### ISSUE TITLE
Visual glitch on Vulkan in Super Kirby Clash [01003fb00c5a8000]

### ISSUE THREAD

**Issue by RocoGreen** [Ryujinx/Ryujinx#3545]
# Bug report

#### Thanks for checking this issue and have a great day <3

# How to reproduce the issue
1. Go to the game
2. Press A on the mission board
3. Select any mission
4. Click on your character
5. "Change role"
6. Issue is here :

![image](https://user-images.githubusercontent.com/52676010/182911543-3860c8d3-6cec-4fd0-be8e-06929aa427d8.png)

## Game info
* Name : Super Kirby Clash
* ID : 01003fb00c5a8000
* Played on language : French

## Versions
* Game Version : v1.0.1
* Firmware : 14.1.2
* Played on Ryujinx Vulkan v1.1.206

## Hardware
* CPU : AMD Ryzen 7 5800H
* GPU : NVIDIA GeForce RTX 3060 Mobile (8GB VRAM)
* RAM : 16G
* OS : Windows 11 (Build 22000)

## PS
* Logs are spamming "Invalid texture format"
* Logs : [Ryujinx_1.1.206_2022-08-04_19-08-19.log](https://github.com/Ryujinx/Ryujinx/files/9261948/Ryujinx_1.1.206_2022-08-04_19-08-19.log)

**Comment by CloneDeath** [comment]
I've been working on this for days, and I'm still learning the code. I suspect this is actually the root cause for a large number of issues.

It looks like the expected texture (handle 12 in the first time launch intro) is not present in the texture buffer, which is causing us to read invalid memory, which is all 1's, which results in reading texture data that shows the format as 0x7FFF... The same thing appears to be happening in this screen too.

I don't know why the texture buffer is not being updated with data. Still digging. But, there's a remote chance this is actually a bug in the game, and, idk, maybe the switch just hides the texture...? I doubt it, but just a thought...

**Comment by GamerzHell9137** [comment]
> I've been working on this for days, and I'm still learning the code. I suspect this is actually the root cause for a large number of issues.
> 
> It looks like the expected texture (handle 12 in the first time launch intro) is not present in the texture buffer, which is causing us to read invalid memory, which is all 1's, which results in reading texture data that shows the format as 0x7FFF... The same thing appears to be happening in this screen too.
> 
> I don't know why the texture buffer is not being updated with data. Still digging. But, there's a remote chance this is actually a bug in the game, and, idk, maybe the switch just hides the texture...? I doubt it, but just a thought...

Theres a PR about it active right now, maybe that solves some of your questions https://github.com/Ryujinx/Ryujinx/pull/3411

**Comment by gdkchan** [comment]
> I've been working on this for days, and I'm still learning the code. I suspect this is actually the root cause for a large number of issues.
> 
> It looks like the expected texture (handle 12 in the first time launch intro) is not present in the texture buffer, which is causing us to read invalid memory, which is all 1's, which results in reading texture data that shows the format as 0x7FFF... The same thing appears to be happening in this screen too.
> 
> I don't know why the texture buffer is not being updated with data. Still digging. But, there's a remote chance this is actually a bug in the game, and, idk, maybe the switch just hides the texture...? I doubt it, but just a thought...

The glitch does not happen on OpenGL according to the post, where it still show the invalid texture format errors, so that's probably not the cause of this issue. I think it is probably caused by a incorrect format on the Vulkan backend (wrong component order or something like that). Probably the easiest way to debug this is doing a RenderDoc capture of this menu running on both OpenGL and Vulkan, and compare the input texture formats.

**Comment by CloneDeath** [comment]
![image](https://user-images.githubusercontent.com/2948533/185697978-5619e5ab-05f3-4849-a176-b3a93ace1d96.png)
You're right. I didn't think to compare against OpenGL. I think the texture format error is still an issue we should fix in general... but since it's happening for both OpenGL and Vulkan, but the textures work on OpenGL, it is likely a red herring to this issue.

I really want to fix the format error issue first, as I see it for a lot of games. Then, I'll likely return to this specific graphical issue next.

**Comment by gdkchan** [comment]
That's fair, but be aware that this might be how the game is supposed to behave. For example, if the texture is only used conditionally on the shader, and the path that does use the texture is not taken in a particular draw, I don't think the texture needs to be actually bound and valid. Of course it's also possible that the texture is supposed to be valid and this is an emulator bug, but it's something to be aware of.

I attempted to reduce the log spam on #3411, but it does not fix the error.

**Comment by gdkchan** [comment]
> texture is not taken in a particular draw, I don't think the texture needs to be actually bound and valid. Of course it's also possible that the texture is supposed to be valid and this is an emulator bug, but it's something to be aware of.

I guess one way to verify if that's the case, is doing a RenderDoc capture and checking how the texture is used on the shader. If it's being used while the descriptor is invalid, then it's probably an emulator issue.

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
