### ISSUE TITLE
Regression: Blossom Tales II displays rainbow/mosaic pixels under NPC characters since 1.1.107

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#3604]
### What's the issue you encountered?

As reported by Discord user kakasita#0149, Blossom Tales 2 displays rainbow/mosaic pixels under NPC characters since version 1.1.107 (PR #3302).

1.1.106:
![image](https://user-images.githubusercontent.com/62343878/185471376-dcb98ccc-c0ff-4fb4-a455-0238426ea9e5.png)

1.1.107:
![image](https://user-images.githubusercontent.com/62343878/185471674-2610e5aa-05fb-4b38-ac21-522ae1fd90ea.png)

1.1.222 (Vulkan):
![image](https://user-images.githubusercontent.com/62343878/185472291-04a0c7fe-3cfd-412d-acc1-9b3662759e49.png)

### How can the issue be reproduced?

Launch Blossom Tales II on Ryujinx version 1.1.107 or newer. 1.1.106 and earlier are not affected.

### Environment?
Tested on OpenGL and Vulkan.
Ryzen 7 5800X
NVIDIA RTX 3080 Ti

**Comment by F1ReB4LL** [comment]
Also broke Disjunction - https://github.com/Ryujinx/Ryujinx-Games-List/issues/3323

![ryujinx_disj11106](https://user-images.githubusercontent.com/39680140/185744249-db2b28bf-deac-49f8-9372-0ba2bc167505.png)
![ryujinx_disj11107](https://user-images.githubusercontent.com/39680140/185744254-6d82d792-0b85-44dc-b132-49688c440812.png)

**Comment by F1ReB4LL** [comment]
Also broke Katana ZERO v1.0.5's loading screen text - https://github.com/Ryujinx/Ryujinx-Games-List/issues/1173

![ryujinx_ktz11106](https://user-images.githubusercontent.com/39680140/185745090-34eb5fe9-11f4-453b-9414-2578ce12d92b.png)
![ryujinx_ktz11107](https://user-images.githubusercontent.com/39680140/185745092-b2c33c4c-49d0-4ded-bcc1-a50bf2d19b66.png)

**Comment by F1ReB4LL** [comment]
Also broke Aggelos - https://github.com/Ryujinx/Ryujinx-Games-List/issues/1946

![ryujinx_agg11106](https://user-images.githubusercontent.com/39680140/185746423-d0f0afce-5380-4c3d-854e-810384d0f171.png)
![ryujinx_agg11107](https://user-images.githubusercontent.com/39680140/185746429-fa58a468-9e61-4f85-83de-b90d87460da1.png)

**Comment by gdkchan** [comment]
It seems that #3610 fixed the issue, so I think it can be closed, unless there's some other texture corruption in the game.

**Comment by F1ReB4LL** [comment]
> It seems that #3610 fixed the issue, so I think it can be closed, unless there's some other texture corruption in the game.

While Blossom Tales II and Katana ZERO 1.0.5 look fine in 1.1.233, both Disjunction and Aggelos are still broken/regressed since 1.1.107.

Disjunction (Vulkan):
![ryujinx_disj11233vlk](https://user-images.githubusercontent.com/39680140/186854008-f7231fa1-7c62-4bb6-abf5-61c3aed82001.png)
Disjunction (OpenGL):
![ryujinx_disj11233ogl](https://user-images.githubusercontent.com/39680140/186854078-f6f9451a-7974-4c68-99ba-38b4e21e31c0.png)
Aggelos (Vulkan):
![ryujinx_agg11233vlk](https://user-images.githubusercontent.com/39680140/186854126-2439e8c4-8cee-42ef-8108-72199a2a3ecf.png)
Aggelos (OpenGL):
![ryujinx_agg11233ogl](https://user-images.githubusercontent.com/39680140/186854151-05eedc90-c3ef-4186-ace0-d1e498c627a8.png)

**Comment by EmulationFanatic** [comment]
Resolved by https://github.com/Ryujinx/Ryujinx/pull/3610
