### ISSUE TITLE
Error 2306-0520 for DNS resolution

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx#3711]
### What's the issue you encountered?

Running Flinthook - 0100307004B4C000 (Ryujinx/Ryujinx-Games-List/issues/1223) gives this error:

![flock_1](https://user-images.githubusercontent.com/39680140/190868577-dfc75b29-e0ca-49db-85f9-7dceacd76e27.png)
![flock_2](https://user-images.githubusercontent.com/39680140/190868583-03dd6621-b6de-476c-ae76-a1714f3d373f.png)

A similar issue https://github.com/Ryujinx/Ryujinx/issues/2913 was fixed by https://github.com/Ryujinx/Ryujinx/pull/2936 but this case is somehow different?

### How can the issue be reproduced?

Just run the game on Ryujinx 1.1.272, the message appears immediately, regardless of whether the "Guest Internet Access" is enabled or not.

### Environment?

- Ryujinx version: 1.1.272</br>
- Game version: 1.0
- System Specs:
  - OS: *Windows 10 21H2*
  - CPU: *i5-11400H*
  - GPU: *NVIDIA RTX 3050*
  - RAM: *24GB*
- Applied Mods : [ No ]

[Ryujinx_1.1.272_2022-09-17_18-58-24.log](https://github.com/Ryujinx/Ryujinx/files/9592232/Ryujinx_1.1.272_2022-09-17_18-58-24.log)

**Comment by EmulationFanatic** [comment]
This is normal, expected behavior on a large number of titles that attempt to connect to Nintendo for online services/eShop etc., since the emulator is blacklisting all Nintendo domains. As your log shows:

```
ServiceSfdnsres GetAddrInfoRequestImpl: Guest network access disabled, DNS Blocked: g249de100-lp1.s.n.srv.nintendo.net
```

Here is Super Smash Bros. Ultimate if you try to enter Online mode:
![image](https://user-images.githubusercontent.com/62343878/190869851-d503125e-9fa4-4426-91e0-507dde02ce58.png)

**Comment by F1ReB4LL** [comment]
Ah, OK, thanks for the explanation.
