### ISSUE TITLE
Save data folder structure

### ISSUE THREAD

**Issue by willyuewu** [Ryujinx/Ryujinx#3975]
First of all, thanks a lot on providing the first application that provides switch emulation on MacOS, it works so good!
But as I am running emulation on multiple platforms, I want to sync my saves, and the save folder structure of Ryujinx is really messy.

#### Overview:
- I hope Ryujinx can follow a more foreseeable save data folder structure, maybe one like what Yuzu did. The root dir is automatically generated, and within it, contain save for each title with the name being the game's ID. This can help transfer save across platforms.
- Currently, the save folder for Ryujinx are complete auto generated, while the name of the folder being the sequence of you open the game. This means if I have the same library on two different machines, the save cannot be transferred with ease.

#### Smaller Details: 
- I don't know if this is depending on the firmware usage of Ryujinx, but if that is not possible, have the ability to let Ryujinx read saves from symlink could also help. Currently, my experience is if the save file is a symlink to elsewhere, Ryujinx can read the save, but will overwrite the symlink as a save file after saving. If it could just write to the location where the symlink links to, it could be much better. 

Both of the things stated are tested on MacOS and Linux (steam deck). I assume it is the same on Windows as well.

**Comment by MutantAura** [comment]
Ryujinx uses the same filesystem and save structure as Horizon and the Nintendo Switch. I would suggest asking other program developers to align with hardware.

**Comment by TopCheddar27** [comment]
I know this has been marked as closed, and honestly I do like the 'ideal' of sticking to the filesystem layout of the original hardware.

However, you have to admit that having the generated folder names be sequential is sub optimal from a user control perspective. Like it or not, internal save folders are not supposed the be user facing on a sandboxed product like the Switch. So using that reasoning for a folder naming schema seems a little flawed. 

Having folder names be based on launch order immediately makes folder syncing tools a non starter. When common practice for save folders for any 'largish' emulation project have been using titleIDs for over two decades, you begin to see why... It makes user interaction predictable, and folder structure is preserved across instances. 

I am not asking for you to reverse any decision on this. Heck, I think making this change this far into your release cycle would confuse end users and cause a lot of mischief in pre existing save stores. I get it. I wouldn't want to do it either.

But the reasoning here is basically "a Nintendo engineer thought of a way to title save folders that would never be touched by a normal user a decade ago". At least admit the utility that would be gained by end users if you did go this direction.

**Comment by MetrosexualGarbodor** [comment]
We do see the utility, but users always ask for this to be changed to folders with gameID names, and as you recognized, this is nowhere close to practical and might just break everything. 

Whenever someone has the time and ingenuity to implement a save syncing solution that doesn't require going against hardware behaviour, that will be it.

**Comment by TopCheddar27** [comment]
> Whenever someone has the time and ingenuity to implement a save syncing solution that doesn't require going against hardware behaviour, that will be it

It's already known exactly what needs to be done to translate your hierarchy to another instance of Ryujinx. It's simply the order you launch it in. Do you see a custom checkbox in syncthing or dropbox that says "translate Ryujinx save folder names"? Generalist tools do generalist things, then let the user adapt. 

While I sympathize with your position, this standoff between hardware filesystem accuracy and user interaction will ultimately reach a boiling point. Maybe it's the saves, maybe it's something else. If the mindset of the team is that every common tool will have to adapt for your schema, I'm not sure you are going to win that battle.

To you (and me), the core of the project are developing precise hardware emulation so that software interacts exactly like it's supposed to. I appreciate that, and am willing to deal with "inconveniences". To your most common user, it is a tool with no moral backing. So they will use another product, if it is of similar quality and allows them predictable syncing. All over a save file directory decision.

It's more of a user retention and portability argument, not a filesystem purity argument.

**Comment by dragoonDorise** [comment]
> We do see the utility, but users always ask for this to be changed to folders with gameID names, and as you recognized, this is nowhere close to practical and might just break everything.
> 
> Whenever someone has the time and ingenuity to implement a save syncing solution that doesn't require going against hardware behaviour, that will be it.

Hi, we are developing a save sync solution for EmuDeck and yeah, this makes it impossible to make it work. Isn't there any other way to do saves that will use the same folder name in every system?

Maybe just add a checkbox so old users won't have issues with their current saves, I know migrating those is scary and it just open a big can of worms.

Thanks for your hard work btw!

**Comment by saildot4k** [comment]
I agree, having the save folder naming scheme follow the gameID makes sense. IMO it makes no sense to follow Horizon/Nintendos method for an emulator when naming the folder the gameID will not break anything.

**Comment by joaociocca** [comment]
I was trying to see if I could find how and come up with a way of doing this, but if the EmuDeck folks tried and failed, me, who's just getting started, just tipping his feet in these waters, have no chance :rofl: 
it's sad, but yeah, thank you and congrats on an amazing work, you folks rock!

**Comment by artemist** [comment]
The first 8 bytes of the ExtraData0 files are the little-endian title ID, then the next 16 bytes are the little-endian user ID. You can use this to map from path to title ID to manage saves. I wrote [a script](https://github.com/artemist/play/blob/canon/scripts/yuzu2ryujinx.py) that does this to move yuzu saves to Ryujinx.

The format is documented [on switchbrew](https://switchbrew.org/wiki/Savegames#Extra_data) and is unlikely to change, so you could parse it in your management code. The most annoying part would probably be creating new directories. I made them manually by opening the game in ryujinx once, but you could write your own ExtraData0 files.

(You can ignore the ExtraData1 files and 1 directories, AIUI those are only for preventing corruption if ryujinx crashes while writing the save)

(I'm not a Ryujinx developer, just an interested user who read some code)

**Comment by joaociocca** [comment]
this just hit me.... in the case of just backing up save data to keep using on another installation of Ryujinx, if the ExtraData0 itself has the title ID, I can just back up the bis/system/save folder and forget about the rest? I was wondering if there was metadata somewhere that linked the sequential data naming folders and the title, but with that ExtraData0 info... 

Let me see if I can explain it better from the start: I thought that since the save folders seem like a sequential number, I'd either have to open the games always in the same order when launching, or rename the folder to fit the correct game.

But with this ExtraData0 info you've mentioned, I wonder if the save game files will be recognized for the correct game in whatever order I open then in case of a new install and recovering the savegame from backup

**Comment by artemist** [comment]
They are recognized fine, IME.
Game saves are in `bis/user/save`. There's some OS saves in `bis/system/save` including Miis and metadata about game save locations. If you don't sync it then "manage saves" won't detect each game's save until you open the game.

I personally sync `system` (keys and user profiles), `sdcard` (not sure what actually uses this), and `bis` (system/user saves and the OS).

**Comment by joaociocca** [comment]
Ah I just realized one thing I finally modded my Switch and was able to extract my saves... but JKSV extracts it in a different way:

![image](https://github.com/Ryujinx/Ryujinx/assets/6473725/93be1652-9a84-45b2-b82d-6cd4b52a0894)

This is my Mario Kart 8 save dump:

![image](https://github.com/Ryujinx/Ryujinx/assets/6473725/2c8173a3-d814-430b-87c3-445b6e318eb7)

No way around, I'll have to manually find out each game's folder on Ryujinx and then copy the savegame files there... 

I thought it weird at first, specially when I saw my FFT:Final Bar Line saves:

![image](https://github.com/Ryujinx/Ryujinx/assets/6473725/83469ca0-4e52-4c5c-9d20-b33b0b5b7580)

But copying these files to Ryujinx's save folder for FFT:FBL did work, I was able to continue my game there from where I had left off on the Switch.

```
(deck@steamdeck ~)$ cd Emulation/saves/Ryujinx/saves/0000000000000009/0/
(deck@steamdeck 0)$ ll
total 68
drwxr-xr-x 2 deck deck  4096 Apr 19 15:44 .
drwxr-xr-x 4 deck deck  4096 Apr 19 15:44 ..
-rw-r--r-- 1 deck deck 22400 Apr 19 15:44 backup.inf
-rw-r--r-- 1 deck deck 30096 Apr 19 15:44 musicBackup.inf
-rw-r--r-- 1 deck deck   384 Apr 19 15:44 proficaBackup.inf
(deck@steamdeck 0)$
```

![image](https://github.com/Ryujinx/Ryujinx/assets/6473725/1d2408b4-2819-48b6-820f-0aa7872ad864)


if anyone can point me an easier way (I've got 51 save folders to import... still trying to decide if I want to sync them or not), I'd be super happy =p

**Comment by joaociocca** [comment]
ok, turns out I found out exactly the thing I thought: there is a file which maps what game goes into what folder (thank you Eku, from Ryujinx Discord!) - the `imkvdb.arc` file. I ended up figuring out a bit of it, trying to come up with a way to bring to Ryujinx the savefiles I exported from my Nintendo Switch using Checkpoint.

@dragoonDorise maybe this could be of use to you, I put the working result on Github, [checkpoint2ryujinx](https://github.com/joaociocca/checkpoint2ryujinx).
