### ISSUE TITLE
[Bug Report] UI/Text looking washed out when upscaling to x2 / x4

### ISSUE THREAD

**Issue by Stimpy7314** [Ryujinx/Ryujinx#4022]
### What's the issue you encountered?

Upscaling to x2 / x4 makes the ui/text washed out. Here's an example: https://imgur.com/a/zjSdtJ4

### How can the issue be reproduced?

By upscaling the game to x2 / x4

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.423</br>

- Game version: Any</br>

- System Specs:
  - OS: Windows 10 22H2
  - CPU: Amd ryzen 5 3600
  - GPU: Gtx 1660 super
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Happens in **ALL** games!

**Comment by MetrosexualGarbodor** [comment]
Resolution scaling will always make UI elements look slightly more pixelated, as they're intended for a 720p screen. That being said the difference here is negligible. Closing as this is not an actual issue.

**Comment by riperiperi** [comment]
This is due to the text being native at 1080p. At 2x it is being bilinearly upscaled when drawn into the textbox, then you are downscaling again, which averages to downscale. If you were actually using a 4k screen at 2x, the text would look the same in both. You can upscale the 1080p image to 4k then flip between them at 1:1 zoom to see this.

This is just how computer graphics work and can't be improved, unless you want to add a random sharpening filter.

**Comment by MutantAura** [comment]
> What is "scaleforce"? I don't think that's a standard.

It's a scaling filter https://github.com/BreadFish64/ScaleFish 

Either way this falls under a feature request once post processing is merged.
