### ISSUE TITLE
General Intel HD question, why does a game crash due to graphic driver and why does updating the graphic driver fix the issue?

### ISSUE THREAD

**Issue by karl-police** [Ryujinx/Ryujinx#4311]
I am trying to understand the technical stuff behind all of this, which is why I create a issue for this in form of a discussion thread.

To roughly give an example. As example Intel HD 520 and Intel HD 620

Why do the driver versions like 26.x cause a crash on something like Pokemon Scarlet and Violet.

But the versions 31.x seems like to not have that issue.

&nbsp;

Mostly crashes occured at different times depending when Vulkan or OpenGL was run, with old Intel driver 26.x versions other than the 31.x ones.

The Intel Graphic drivers depend on the Intel CPU. But for a quick overview of certain drivers, here's a link: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html just note that the actual Intel Graphic Driver depends on the Intel CPU.

For searching these drivers, you also want to click on "View download options" to see also .zip and Release Notes and etc.

Those are generic drivers, if requirements are met they work with all systems that use it. But for laptops, it depends whetever the brand customized the installer in some sort of way.

&nbsp;

Someone told me about this https://github.com/KhronosGroup/Vulkan-Guide that there's some sort of documentation. Maybe, it contains answers not sure.

&nbsp;

But regarding the crashes.

Is it because of the graphic driver? Or is it because of Ryujinx?

And why?

Updating the graphic driver fixes crashes. But the question is why, incase the before one was confusing.

But I am asking if those crashes occur because Ryujinx doesn't handle older drivers. Or if it really is because of the graphic driver.

And the question then would be why.

**Comment by MetrosexualGarbodor** [comment]
This is not a forum, join [discord](https://discord.gg/ryujinx) for this kind of thing.

**Comment by gdkchan** [comment]
I could be due to a bug in the old driver that was fixed on the newer one, it could be because of some feature that the emulator requires and the old one did not support, but the new one does. It could also be some issue on the emulator that the newer drivers somehow avoids by doing things in a different way (although of all possibilities, this is the less likely one). We would need to take a look at the issue to figure out why, but given that it already works on the newer driver, I don't think it's worth the effort.
