### ISSUE TITLE
[Feature Request] restructure the save folder structure based on game id

### ISSUE THREAD

**Issue by branchus** [Ryujinx/Ryujinx#4407]
### Overview

At moment, all the save folders are numbered from 000....001, 000...002, 000..003 onwards.

if a game has been deleted, the save folder will stay, even manually deleted it, it will be recreated (empty), I understand the reason to do this. but I would think it make more sense the save folder are arranged by the game id.

### Smaller Details

if the above feature got implemented, it may break current implementation, so maybe have a option toggle. but in the long

Also I noticed that in the games folder, games are already listed by their game id, so all the info should already be there.

### Nature of Request

Tring to find a save is hard
to clean up completed game save is a nightmare as I had more than 100 folders sitting under the save folder. and all I can see is a sequence number.

### Why would this feature be useful?

It will help to arrange the saves, prevent useless folders to be created. and easy locate the saves in the file system (even when the game has been deleted already)

**Comment by MutantAura** [comment]
The filesystem structure is accurate to the Switch's own methods of handling its saves. There is no interest in using an inaccurate file structure.

**Comment by vesper8** [comment]
I understand the desire to do things exactly as they are done on the original system.. but this causes so many user experience headaches as detailed by the OP.. Also, for example when trying to sync save games between two computers, this approach makes that very difficult. Yuzu made a compromise here and designed their save folders to have unique and predictable names and that's IMO a pro rather than a con.
