### ISSUE TITLE
[Bug] White flashes during gameplay in Bayonetta 3

### ISSUE THREAD

**Issue by FatCache** [Ryujinx/Ryujinx#4518]
### Description of the issue
![Ryujinx_wKjJzQPSIM](https://user-images.githubusercontent.com/8831324/223293455-5f99d132-26cc-4f5c-9379-9ae86ecda07f.png)

Playing Bayonetta 3, I am getting white flashes during the game play. I searched online for a fix and did the recommendation. 

- Enable Texture Compression
- Graphic Backend Multithreading On
- Vulkan

I do C# development for a living on the WinForm side and bit of ASP.NET. I am willing to dive into the code to figure out a fix. Guidance on part of the application to debug will be appreciated.

### Reproduction steps

Start the game and waiting for right scene to begin. The flashes appear. 

### Log file

[Ryujinx_1.1.650_2023-03-06_20-06-14.log](https://github.com/Ryujinx/Ryujinx/files/10904256/Ryujinx_1.1.650_2023-03-06_20-06-14.log)

### OS

Windows 11

### Ryujinx version

1.1.650

### Game version

1.1

### CPU

RYZEN 5 5600X

### GPU

6800 XT

### RAM

32 GB

**Comment by gdkchan** [comment]
Are you talking about the god rays issue that is mentioned here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4129 ?

**Comment by gdkchan** [comment]
The way to debug graphical issues like that is doing RenderDoc captures. You capture a frame that is rendered incorrectly, and then if possible, capture a correct frame for reference. Then you can compare the draws and try to figure out what is wrong. From there you can try fixing it in the code. It is not exactly a simple process, especially if you're not familiarized with those graphics APIs and 3D rendering in general.

As a side note, not all GPUs seems to have this issue. AMD seems to have it in all GPUs, NVIDIA only on only on RTX 3xxx and RTX 4xxxx, and only on more recent drivers (I don't remember the version where it started happening). From what I tested Apple Silicon does not have the issue. I wasn't able to test on Intel integrated because it crashes, at least on Windows.

**Comment by Squall-Leonhart** [comment]
This might be a situation where VK_KHR_SHADER_FLOAT_CONTROLS can help.

**Comment by FatCache** [comment]
> Are you talking about the god rays issue that is mentioned here: [Ryujinx/Ryujinx-Games-List#4129](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4129) ?

Yes, I am referring to the same issue.

>  especially if you're not familiarized with those graphics APIs and 3D rendering in general.

I am not familiar with any graphic APIS or 3D in general, I guess I will need to pass this to the pros.

**Comment by AcK77** [comment]
It's still the case ?

**Comment by FatCache** [comment]
> It's still the case ?

I haven't tried it again, did a fix get checked in?
