### ISSUE TITLE
[Bug] Fire Emblem Engage 1.3 crashing when using donation section of bulletin board

### ISSUE THREAD

**Issue by NicoleKCat** [Ryujinx/Ryujinx#4531]
### Description of the issue

Whenever you attempt to use the donations section of the bulletin board in somniel, you get thrown an invalid memory region exception. 
You need to specifically select the donation subcategory, the other categories don't cause a crash. 

This only occurs when update 1.3 is applied. 

Additionally, yuzu (ver 1366)  is able to open the donation board without a crash. 

### Reproduction steps

- Enter Somniel
- Either walk or fast travel to the bulletin board located in the cafe. 
- Select "Donations."
- You do an oopsie woopsie. 

### Log file

[Ryujinx_1.1.651_2023-03-10_12-55-33.log](https://github.com/Ryujinx/Ryujinx/files/10946177/Ryujinx_1.1.651_2023-03-10_12-55-33.log)

### OS

Microsoft Windows 10 10.0.19045 Build 19045

### Ryujinx version

1.1.651

### Game version

1.3

### CPU

AMD Ryzen 9 3900X 12-Core Processor, 4000 Mhz, 12 Core(s), 24 Logical Processor(s)

### GPU

NVIDIA GeForce RTX 2070 SUPER

### RAM

32 GB

### List of applied mods

There's a few mods installed but it's not applicable here, as the aforementioned UI category crashes regardless of mod usage in 1.3, and does not when 1.3 is removed. 

- [Battle outfits and more ver 1.7](https://gamebanana.com/mods/download/424968#FileInfo_946302)
- Dialogue localization fix / "uncensor" version 1.3, I'm not linking this for reasons. 
- [NDA - No Dogs Allowed version 1.3](https://gamebanana.com/mods/download/430000#FileInfo_942934)
- [Double SP Gain version 1.3](https://gamebanana.com/mods/download/425109#)
- [Rebalanced Summon Rates - "Rigged" version 1.3](https://gamebanana.com/mods/download/430644#)
- [SP Conversion for everyone ](https://gamebanana.com/mods/download/431221#FileInfo_946439)
- Pareo Swimsuit Edited - Mesh only, more reasons. 

### Additional context?

- I currently only have the first region unlocked for the bulletin board, may or may not be relevant. 
- Donation level for Firene is 3, may or may not be relevant. 
- My cat is currently snoring while resting peacefully, may or may not be relevant.

**Comment by gdkchan** [comment]
It would be nice to have a save to allow reproducing the issue easily. Whoever is going to look at this issue might not have played the game and might not have a save on a place that can reproduce the issue. If it takes time to get there, having a save is useful.

> Additionally, yuzu (ver 1366) is able to open the donation board without a crash.

I'm not sure what exactly this information adds. Generally what we care about is whenever the game functions correctly on hardware. I'm assuming it does since it's unlikely they would release a broken update. Also AFAIK yuzu ignores invalid memory access, so this issue would manifest itself differently there (it might not result in a crash).

> I'm not linking this for reasons.

We're not here to judge which mods you use. This is an emulator, if a mod works on hardware but not on the emulator, then that's a bug that we need to fix. It should be fine to link the mod as long it does not contain any illegal/copyrighted content. You said that the mods does not have any impact on this issue so you don't need to link them here, I'm just mentioning this for future reference.

**Comment by Foul-Tarnished** [comment]
I can do donations without crash, at least just after loading ingame directly into somniel.
But I have other crashes as mentionned in #4536

**Comment by NicoleKCat** [comment]
I lied, it's actually the [NDA - No Dogs Allowed mod](https://gamebanana.com/mods/430000) causing the issue. 

It's listed as 1.3 compatible and as other software was loading the mod my assumption was it wasn't the problem. I was unaware that it ignored invalid memory access errors. 

From the mod listing:

> _1.30 changed nothing relevant, so this is still fully compatible with 1.10-1.30. Base game is probably compatible too, but have not checked._

It seems strange to me that the modified file is accessed at all while opening the donation board. 

> _It would be nice to have a save to allow reproducing the issue easily_

Fair, though it seems like this is something that could be part of the issue template itself. 

[Fire Emblem Engage 1.3 no dogs allowed crash.zip](https://github.com/Ryujinx/Ryujinx/files/10951886/Fire.Emblem.Engage.1.3.no.dogs.allowed.crash.zip)

I've mentioned the error to the mod author, I'm just putting this information here on the off-chance it's not something wrong on the mod end itself.
