### ISSUE TITLE
[Bug] Fire emblem engage 1.3 crash "errorOutOfDeviceMemory"

### ISSUE THREAD

**Issue by Nerboruto** [Ryujinx/Ryujinx#4677]
### Description of the issue

even repeating same stage, vram usage always growing until it runs OutOfDeviceMemory and causes crash.
TextureRecompression on.

### Reproduction steps

load stage and repeat

### Log file

[Ryujinx_1.1.708_2023-04-14_16-20-32.log](https://github.com/Ryujinx/Ryujinx/files/11234413/Ryujinx_1.1.708_2023-04-14_16-20-32.log)

### OS

Windows 10.0.19041

### Ryujinx version

1.1.708

### Game version

1.3

### CPU

xeon e3-1230 v3 4c8t

### GPU

quadro p600 2gb (gtx 1050)

### RAM

12gb

**Comment by OldManKain** [comment]
As stated in discord and here you do not have enough Vram on your GPU for this game, please use discord for troubleshooting issues.

**Comment by Nerboruto** [comment]
> As stated in discord and here you do not have enough Vram on your GPU for this game, please use discord for troubleshooting issues.

but what kind of answer would that be... I argued with possible solutions to the problem... if I complete the stage before the vram fills up I can play indefinitely without crashing because vram is emptied when loading new stage....

**Comment by gdkchan** [comment]
> is it not possible to recycle old textures and overwrite them?

I'm not sure how that would help. We can only use a texture for something else if its not in use anymore. Right now the textures that are no longer needed are deleted (freeing the VRAM it used). If we used the texture for something else instead, it wouldn't really change the VRAM usage, at most it would be a performance optimization.

> or allocate system memory when vram is full?

It's possible to do that, but it comes at a performance cost since VRAM is faster. Allocating on system memory when the VRAM is full and keeping the texture there forever wouldn't be too hard, but also wouldn't perform the best. Migrating textures that are not used often to system memory when the VRAM is full would perform better, but would be harder to implement. Also older NVIDIA GPUs seems to just show extremely corrupted graphics and then eventually crash when you get close to the VRAM limit, so the "VRAM is full" condition wouldn't work on those GPUs, we would need to somehow detect when the usage is *close* to filling all the VRAM.

Another possible approach is dropping higher mipmap levels of the texture to reduce the size. It would degrade the texture quality (which texture recompression also does), but would have the advantage of being faster than texture recompression.

**Comment by Nerboruto** [comment]
I also tried opengl but it crashed for some other reason. 
however it is strange because in the stage there are always the same textures, when I repeat it vram usage increases continuously until it crashes. 
in my opinion some solution needs to be found... maybe use system ram at the same time with some texture logic that avoids crashes even at the cost of slowing down. Thanks for reply.

**Comment by Nerboruto** [comment]
> > is it not possible to recycle old textures and overwrite them?
> 
> I'm not sure how that would help. We can only use a texture for something else if its not in use anymore. Right now the textures that are no longer needed are deleted (freeing the VRAM it used). If we used the texture for something else instead, it wouldn't really change the VRAM usage, at most it would be a performance optimization.
> 
> > or allocate system memory when vram is full?
> 
> It's possible to do that, but it comes at a performance cost since VRAM is faster. Allocating on system memory when the VRAM is full and keeping the texture there forever wouldn't be too hard, but also wouldn't perform the best. Migrating textures that are not used often to system memory when the VRAM is full would perform better, but would be harder to implement. Also older NVIDIA GPUs seems to just show extremely corrupted graphics and then eventually crash when you get close to the VRAM limit, so the "VRAM is full" condition wouldn't work on those GPUs, we would need to somehow detect when the usage is _close_ to filling all the VRAM.
> 
> Another possible approach is dropping higher mipmap levels of the texture to reduce the size. It would degrade the texture quality (which texture recompression also does), but would have the advantage of being faster than texture recompression.

I also tried opengl but it crashed for some other reason.
however it is strange because in the stage there are always the same textures, when I repeat it vram usage increases continuously until it crashes.
in my opinion some solution needs to be found... maybe use system ram at the same time with some texture logic that avoids crashes even at the cost of slowing down. Thanks for reply.

**Comment by Nerboruto** [comment]
I improved it slightly by lock dynamic resolution to 0.9 in params.xml.bundle unity engine.
it takes longer to go out of memory...
