### ISSUE TITLE
[Bug] Ryujinx crash when game started

### ISSUE THREAD

**Issue by scarled** [Ryujinx/Ryujinx#4988]
### Description of the issue

When I wanted to start the game the Ryujinx crash after a couple a seconds (the games docent start)

### Reproduction steps

I just open the settings and added the nsp file in the user interface/game directory

### Log file

[Ryujinx_ 1.1.0-macos1_2023-05-16_11-23-36.log](https://github.com/Ryujinx/Ryujinx/files/11490871/Ryujinx_.1.1.0-macos1_2023-05-16_11-23-36.log)
[Ryujinx_ 1.1.0-macos1_2023-05-16_11-23-53.log](https://github.com/Ryujinx/Ryujinx/files/11490872/Ryujinx_.1.1.0-macos1_2023-05-16_11-23-53.log)
[Ryujinx_ 1.1.0-macos1_2023-05-16_11-27-19.log](https://github.com/Ryujinx/Ryujinx/files/11490873/Ryujinx_.1.1.0-macos1_2023-05-16_11-27-19.log)

### OS

Mac ventura 13.3.1 is a Apple M1 Max 

### Ryujinx version

1.1.0

### RAM

12GB

**Comment by scarled** [comment]
I actually find a way to go further ( I disable some gpu settings) but now its crash from other reason, from what I see in the logs is from controller settings
[Ryujinx_ 1.1.0-macos1_2023-05-16_11-37-27.log](https://github.com/Ryujinx/Ryujinx/files/11491012/Ryujinx_.1.1.0-macos1_2023-05-16_11-37-27.log)
[Ryujinx_ 1.1.0-macos1_2023-05-16_11-38-10.log](https://github.com/Ryujinx/Ryujinx/files/11491013/Ryujinx_.1.1.0-macos1_2023-05-16_11-38-10.log)
[Ryujinx_ 1.1.0-macos1_2023-05-16_11-41-21.log](https://github.com/Ryujinx/Ryujinx/files/11491014/Ryujinx_.1.1.0-macos1_2023-05-16_11-41-21.log)

**Comment by AcK77** [comment]
In the OP the error is `System.Exception: Unexpected result "HV_UNSUPPORTED"` you have to enable it to be able to use Ryujinx under macOs if `UseHypervisor` settings is enabled. For the second post with other log files, the issue seems to be related to your controller settings. You can try to delete `Config.json` file and try again with the right settings.
I suggest you to come on our Discord for support.
Thanks.
