### ISSUE TITLE
[Bug] Smash Bros. Ultimate linux vulkan crash whenever a Finish Zoom occurs

### ISSUE THREAD

**Issue by Duex** [Ryujinx/Ryujinx#5096]
### Description of the issue

When running Smash on a Steam Deck using the Vulkan renderer, if the Finish Zoom mechanic occurs during a match (i.e. the camera zooms on a powerful attack that's likely to kill), for some reason both the game and emulator just freezes, along with a brief screen-flicker.  This eventually leads to a system-wide black screen, and if let sit for long enough, a full-on system reboot.

I don't know if this crash is unique to SteamOS, or if it also happens in other versions of Linux.

### Reproduction steps

Run the linux version of Ryujinx in SteamOS, render in Vulkan, launch Smash Ultimate, and get a Finish Zoom to occur in-game.  

[See this video for an easy way to reproduce this.](https://drive.google.com/file/d/165oNVBLR_ZeI9h57lixwMlwK8NxQKbiy/view?usp=sharing)

### Log file

[Ryujinx_1.1.819_2023-05-25_02-41-35.log](https://github.com/Ryujinx/Ryujinx/files/11562012/Ryujinx_1.1.819_2023-05-25_02-41-35.log)

### OS

SteamOS

### Ryujinx version

1.1.811

### Game version

13.0.1

### CPU

Steam Deck

### GPU

Steam Deck

### RAM

16gb

**Comment by WatDuhHekBro** [comment]
I can confirm that it also causes the same type of crash on Manjaro. Specifically, all versions of Ryujinx 1.1.805+, this doesn't happen on 1.1.804. This leads me to believe it might be related to #5143, since one of the last lines of the crash is `|E| .NET ThreadPool Worker radv/amdgpu: The CS has been cancelled because the context is lost.` Sometimes I'll be able to log back in, but other times, I'll get `$DISPLAY is not set or cannot connect to the X server.`

**Comment by Duex** [comment]
> I can confirm that it also causes the same type of crash on Manjaro. Specifically, all versions of Ryujinx 1.1.805+, this doesn't happen on 1.1.804. This leads me to believe it might be related to #5143, since one of the last lines of the crash is `|E| .NET ThreadPool Worker radv/amdgpu: The CS has been cancelled because the context is lost.` Sometimes I'll be able to log back in, but other times, I'll get `$DISPLAY is not set or cannot connect to the X server.`

TY for testing this in lower versions numbers, i'll try using 1.1.804 as a workaround for now

**Comment by Duex** [comment]
> I can confirm that it also causes the same type of crash on Manjaro. Specifically, all versions of Ryujinx 1.1.805+, this doesn't happen on 1.1.804. This leads me to believe it might be related to #5143, since one of the last lines of the crash is `|E| .NET ThreadPool Worker radv/amdgpu: The CS has been cancelled because the context is lost.` Sometimes I'll be able to log back in, but other times, I'll get `$DISPLAY is not set or cannot connect to the X server.`

TY for testing this in earlier versions, i'll try using 1.1.804 as a workaround for Smash for now
(whoops did NOT mean to hit the close button >.<)

**Comment by WatDuhHekBro** [comment]
Well something strange happened: After testing 1.1.872, I tested 1.1.805 again out of curiosity, and apparently I don't have this issue anymore. The only thing I remember happening in-between then is a system update on Manjaro, so it seems like that fixed my issues. I don't know if SteamOS had a similar type of update since then.
