### ISSUE TITLE
[Bug] TOTK Visual glitch with old GPU

### ISSUE THREAD

**Issue by malandrin970** [Ryujinx/Ryujinx#5178]
### Description of the issue

![image](https://github.com/Ryujinx/Ryujinx/assets/133511751/b9030e95-0972-4c49-aaac-6c9074f5aa7e)

When I put anisotropic filtering x16 these strange colors are less present, but they are still visible in the distance. 
Other than that the game is running fine. In front of Link you can notice a strange shadow who moves with him.

### Reproduction steps

Weird colors

### Log file

[Ryujinx_1.1.844_2023-05-31_17-28-14.log](https://github.com/Ryujinx/Ryujinx/files/11616023/Ryujinx_1.1.844_2023-05-31_17-28-14.log)

### OS

Windows 10

### Ryujinx version

1.1.844

### Game version

1.0.0

### CPU

AMD Ryzen 5 5600

### GPU

R9 380

### RAM

32gb

### List of applied mods

no mods

**Comment by AcK77** [comment]
What if you let the anisotropic filtering to automatic ?

**Comment by amayra** [comment]
is this is related to shader interlock and FSI that is still missing in AMD driver only 

the good news : this will be fixed 

the bad news : this will be fixed in linux only

**Comment by jackandcarter** [comment]
@amayra is this because people find it difficult to create modified drivers/kext on macOS? If updating an AMD driver on linux can be done with code it can also be done on Mac, I understand apple no longer does AMD driver updates, but that doesn't mean we can't ourselves. As long as the kernel doesn't need anything I don't see why not right?

**Comment by MutantAura** [comment]
This GPU is end of life and out of driver support from AMD. 
Stick to auto anisotropic filtering.
