### ISSUE TITLE
[Bug] TOTK 1.1.2 Doesnt want to run cheats

### ISSUE THREAD

**Issue by JakeBreathild** [Ryujinx/Ryujinx#5283]
### Description of the issue

Since the 1.1.17~ Update from Ryujinx TOTK doesnt want to run cheats i tried already changing the cheat file and cleaning PPTC and Shaders (Just to see if that would help) but nothing changes, i have multiple cheats active such as: Infine Zonai Devices and Zonai device Durability, Item Multiplication x8, Ignore item requirement for Great Fairys and Horses, etc.

 

### Reproduction steps

Put a cheat on, and try its effects if it doesn't work you know the system is still broken. 

### Log file

cant play with logs on

### OS

Windows 11 Pro 22H2

### Ryujinx version

1.1.882

### Game version

1.1.2

### CPU

i5-9400F @ 2.90GHz Turbo 4.0GHz~

### GPU

Nvidia Geforce GT 710 2GB LP (No i dont have money for a new one) Outdated Drivers

### RAM

8GB DDR4

### List of applied mods

Nothing

### Additional context?

Here you have a Pastebin that i send to the cheat file creator too, it has the cheats an says which ones i had active: https://pastebin.com/mUrhHDpx

**Comment by AcK77** [comment]
It will be hard to help you without a log file, and btw « can’t play with logs on » isn’t valid at all since they common logging doesn’t affect performance at all...
Anyway, since you use an updated version of Totk, you have to use updated cheat code for this specific version too.

I suggest you to come to our discord for support since it’s not a Ryujinx issue. Thanks.
