### ISSUE TITLE
Ryujinx Crash when using SMO-Exlaunch-Base Mod

### ISSUE THREAD

**Issue by Octoklingjs** [Ryujinx/Ryujinx#5466]
### Description of the issue

I attempted to create a mod using the [SMO-Exlaunch-Base repository](https://github.com/CraftyBoss/SMO-Exlaunch-Base/) for Ryujinx, but I encountered a problem. Whenever I build and test the mod, Ryujinx crashes unexpectedly. It's worth noting that the mod works fine on the Nintendo Switch.

### Reproduction steps

1. Clone the [SMO-Exlaunch-Base repository](https://github.com/CraftyBoss/SMO-Exlaunch-Base/)
2. Build the mod.
3. Put the mod on Ryujinx.
4. Launch Super Mario Odyssey.
5. Observe the crash occurring in Ryujinx.

### Log file

[Ryujinx_1.1.964_2023-07-18_14-13-52.log](https://github.com/Ryujinx/Ryujinx/files/12094419/Ryujinx_1.1.964_2023-07-18_14-13-52.log)

### OS

Windows 11 22H2 build 22621.1992

### Ryujinx version

1.1.965

### Game version

1.0.0

### CPU

Intel i5-8300H

### GPU

GTX 1050 (Laptop)

### RAM

8GB

**Comment by TSRBerry** [comment]
Got it!
![ryujinx_capture_2023-08-01_21-52-37](https://github.com/Ryujinx/Ryujinx/assets/20988865/cc8d4f97-02d0-4ca1-88f2-fda8d658e2ba)

The error code from SMO-Exlaunch-Base was misleading, because it was used twice. 
1. `result::TooManyStaticModules`
2. unconditionally in the exception handler

So after I figured out the real error code (`InvalidHandle` as @gdkchan already said), creating a fix was easy.

The PR will be up in a few minutes!
