### ISSUE TITLE
[Feature Request] Remember Previous Volume Level After Un-muting

### ISSUE THREAD

**Issue by Sponge-bink** [Ryujinx/Ryujinx#5745]
### Overview

Ryujinx now ignores the previous volume level after muting and unmuting the game. 

### Smaller details

none

### Nature of request

Adjust the volume level to, say, 50%, mute the game and unmute (by clicking the `Vol: n%` button), it sets the volume level back to 100%. 

### Why would this feature be useful?

It would be great to maintain the same volume level after unmuting.

**Comment by rmg-x** [comment]
I'm not able to reproduce this bug with version 1.1.1059
I set the volume via `Options -> Settings -> System -> Volume` and then mute/unmute which keeps the value.

This code handles the mute functionality:
https://github.com/Ryujinx/Ryujinx/blob/638be5f296bf52943da4366699d33f1e8656e00c/src/Ryujinx/Ui/MainWindow.cs#L1285-L1292

**Comment by MutantAura** [comment]
I presume they mean if you change the volume via the in-bar flyout, mute, then unmute, the volume will return to whatever is set via config, not whatever was selected via flyout.
This is sort of intentional though as all of the adjustments that can be made via the bottom bar are designed to _not_ be saved, and only used for that session.

Perhaps it would be better to store a temporary pre-mute variable and load that instead of going directly to `ConfigurationState`. In both scenarios this would result in the correct value being returned.

**Comment by rmg-x** [comment]
> I presume they mean if you change the volume via the in-bar flyout

How do you toggle the in-bar flyout?

**Comment by MutantAura** [comment]
It is present when using the Avalonia frontend, which I assume they are using.
