### ISSUE TITLE
[Bug] Fullscreen toggle is bound to the A button in a xbox controller after pressing ctrl+tab

### ISSUE THREAD

**Issue by jzatarain** [Ryujinx/Ryujinx#5777]
### Description of the issue

Pressing A toggles fullscreen

### Reproduction steps

Open any game, press ctrl+tab.
Go back to ryujinx
press A in your controller, and the fullscreen mode is toggled

### Log file

[Ryujinx_1.1.1048_2023-10-07_15-34-24.log](https://github.com/Ryujinx/Ryujinx/files/12838989/Ryujinx_1.1.1048_2023-10-07_15-34-24.log)

### OS

windows 10

### Ryujinx version

1.1.1048

### Game version

1.0.0

### CPU

amd ryzen 5 56600g

### GPU

nvidia rtx 4070

### RAM

16gb

### Additional context?

I tried with 2 xbox controllers

**Comment by scoofz** [comment]
I can confirm that this, it's extremely annoying. It can also break if you switch to another app but not always. I have to restart the emulator a few times every time because the controller stops working...

**Comment by MutantAura** [comment]
Ryujinx has no way of passing controller inputs to the UI framework, or to the window in general. 

If your controller is able to interact with the window, then a third party program such as Steam, BetterJoy, DS4Windows or the Xbox game bar etc. is messing with your controller or intercepting the inputs.

**Comment by scoofz** [comment]
> Ryujinx has no way of passing controller inputs to the UI framework, or to the window in general.
> 
> If your controller is able to interact with the window, then a third party program such as Steam, BetterJoy, DS4Windows or the Xbox game bar etc. is messing with your controller or intercepting the inputs.

I don't understand, I don't have any of these apps open (or even installed for that matter. What's also funny is that this is the kind of issue that only ever happened in Ryujinx. Any other emulator work just perfectly with my controllers

**Comment by MutantAura** [comment]
I don't understand either, but I can assure you that whatever the issue is, it is not within this program.
There is no ability within Ryujinx to control _anything_ about the GUI via a controller. 

The two shortcuts for fullscreen in Ryujinx are F11 and Alt+Enter. If you are triggering fullscreen, it is because the framework thinks you have pressed one of those combos.

**Comment by scoofz** [comment]
Ok I think you misunderstood the issue. We're saying that when we put the emulator in full screen with our mouse, the controller stops working in the emulator....

**Comment by MutantAura** [comment]
I did not misunderstand this issue.
The subject states that pressing A on their controller causes the window to fullscreen, you appear to be having an entirely unrelated problem which is not related to this page. If your issue is not the same as the the OP then please do not comment on it. Either find the relevant issue that someone else has opened, or open a new issue describing your own bug.

**Comment by jzatarain** [comment]
Closing steam seems to fix the issue

**Comment by scoofz** [comment]
My bad, I replied to the wrong thread...
