### ISSUE TITLE
Anti-Aliasing Setting In config

### ISSUE THREAD

**Issue by BetterWaifus** [Ryujinx/Ryujinx#584]
There is no way to change the amount of Anti-Aliasing.

**Comment by gdkchan** [comment]
I don't think this should be exposed as a config option. The game can enable or not anti aliasing by writing the respective gpu registers. We should do what the game tell us to do, in order to render the scene as close as possible to a real switch. Currently, this is not supported because it's a minor feature. If such a config option existed, it would be an override to what the game set on the gpu.

**Comment by BetterWaifus** [comment]
@gdkchan could this setting be released in a special version of Ryujinx?
