### ISSUE TITLE
[Bug][Regression] Digimon Story Cyber Sleuth: Complete Edition - 1.1.1066 causes graphics regression

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [Ryujinx/Ryujinx#5908]
### Description of the issue

In Digimon Story Cyber Sleuth: Complete Edition on OpenGL (may affect Vulkan as well, but unable to test), texture colors occasionally get garbled upon reloading the map - be it by getting into a battle, or changing areas, and can sometimes, but not always, be corrected by doing the same thing, often requiring changing areas 5-6 times before temporarily correcting itself, and sometimes garbling again immediately after the next transition again. Here is a screenshot of one example of this 'garbling':
![image](https://github.com/Ryujinx/Ryujinx/assets/1993598/dd19ef1a-0bc9-41ee-8db7-0ba711540e72)

This issue is a regression. I started having this issue after updating to 1.1.1061 to 1.1.1069 2 weeks ago, and have tested both 1.1.1065, where the issue does not happen anymore, and 1.1.1066, where the issue starts happening. The 'flushes', or at least some of them, seem to actually be necessary after all, as without them, this mess is what you get with this game. I will be using 1.1.1065 until this is fixed, but I thought I would let everyone know.

### Reproduction steps

1. Install Ryujinx 1.1.1066 or above
2. Run Digimon Story Cyber Sleuth: Complete Edition, with this save: [0000000000000005.zip](https://github.com/Ryujinx/Ryujinx/files/13302399/0000000000000005.zip), using OpenGL as the graphics backend.
3. Change areas by going north into the detective agency (pictured above in the issue description).
4. Change areas again by leaving the agency.
5. Enter the agency again.
6. Exit the agency again.
7. Keep on the left side of the screen and move south until you get a prompt to press A, then press A, which will take you to the DigiLab.
8. Move away from the starting point in the DigiLab, then move back until you get an A button prompt again; press A to leave the DigiLab.
9. Repeat steps 3 to 8 until the graphics get garbled. It will eventually happen, just keep at it.

### Log file

[Ryujinx_1.1.1072_2023-11-08_18-16-23.log](https://github.com/Ryujinx/Ryujinx/files/13302420/Ryujinx_1.1.1072_2023-11-08_18-16-23.log)

### OS

Windows 10 22H2 (64-bit)

### Ryujinx version

1.1.1066

### Game version

1.0.3

### CPU

i7-7700

### GPU

MSI NVIDIA GeForce GTX 1060 3GB

### RAM

16GB

### Additional context?

Some cheats were added, but this issue started long after cheats were started being used, so they are most certainly unrelated.

**Comment by gdkchan** [comment]
There is no simple solution here. It was already not flusing on unmap before, which was already "incorrect", in the sense that if the CPU reads the data after it has been unmapped, it won't have the GPU changes (as right now the emulator just pretends that if GPU memory was unmapped, game doesn't care about the data anymore). I could also allow it to flush even after the data has been unmapped from GPU, but this is actually more "dangerous" since it could corrupt CPU data if the memory is already being used for something else (in theory it shouldn't happen since any access to the memory should trigger flush before it is modified, but the "ignore flush on unmap" behaviour was added for a reason). And from my experience this kind of change always breaks something, with 5000+ games on the Switch library, it's pretty much impossible to test them all.
