### ISSUE TITLE
[Bug] Nintendo 64 nso apps crash on fw 13+

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#6021]
### Description of the issue

all the nintendo 64 nso apps crash on firmware 13+
Affects:
- Nintendo 64 - Nintendo Switch Online [0100C9A00ECE6000]
- NINTENDO 64 Nintendo Switch Online [010057D00ECE4000] [JP]
- NINTENDO 64 Nintendo Switch Online 18+ [010037A0170D2000]

### Reproduction steps

run nintendo 64 nso on fw 13+

### Log file

12.1.0: [Ryujinx_1.1.1098_2023-12-08_19-35-47.log](https://github.com/Ryujinx/Ryujinx/files/13620230/Ryujinx_1.1.1098_2023-12-08_19-35-47.log)

13.0.0: [Ryujinx_1.1.1098_2023-12-08_19-31-23.log](https://github.com/Ryujinx/Ryujinx/files/13620204/Ryujinx_1.1.1098_2023-12-08_19-31-23.log)

17.0.1: [Ryujinx_1.1.1098_2023-12-08_19-34-16.log](https://github.com/Ryujinx/Ryujinx/files/13620214/Ryujinx_1.1.1098_2023-12-08_19-34-16.log)

### OS

Arch Linux

### Ryujinx version

1.1.1098

### Game version

2.13.0

### CPU

AMD Ryzen 9 7900X3D

### GPU

AMD RX 6600 XT

### RAM

64gb

### Additional context?

Works on 1.1.1060
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/09cd9fa3-75db-4a5e-950f-44dbe276ccff)
Works on 12.1 or lower
![image](https://github.com/Ryujinx/Ryujinx/assets/100526773/fdc64580-1d38-4838-8d9e-181cade0f0e7)

**Comment by piplup55** [comment]
> Does it work with PPTC disabled?

works with pptc disabled, doesn't work with it enabled even with a full pptc clear

**Comment by pHANTOMpHREAK9P** [comment]
It does not work with PPTC disabled on my end.  The game initially loads, but choosing a game to run instantly crashes the emulator.

I am testing using the same Ryujinx version and game version as listed by OP.  I have also tested it with the new update released today bringing the game to version number 2.14.0 and the problem is still the same.  Main difference is that I am on Windows 10 versus OP on Arch Linux.
