### ISSUE TITLE
[Bug]Touhou Genso Wanderer Reloaded [01004E900B082000] nothing but a black screen

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6157]
### Description of the issue

nothing but a black screen

### Reproduction steps

just load game

### Log file

[Ryujinx_1.1.1117_2024-01-21_15-43-13.log](https://github.com/Ryujinx/Ryujinx/files/14000494/Ryujinx_1.1.1117_2024-01-21_15-43-13.log)

### OS

Windows 10

### Ryujinx version

1.1.1117

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
Based on your log file, it's seems a video is playing and you exited the game while the video is playing.
Unsupported video at boot is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/645 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
