### ISSUE TITLE
[Bug] Unable to play Persona 4g with any input

### ISSUE THREAD

**Issue by Zhusiyu123** [Ryujinx/Ryujinx#6276]
### Description of the issue

During the playing of Persona 4g always jumping out a small window says'Your current configuration is invalid.Open settings and recongifigure your inputs.Docked mode set.Hanheld control should be diasbled'.I double checked the setting which was absolutely no problem and checked in differernt games.The clu is they all work with it. 

### Reproduction steps

It was working at 7th feb but soonly unable to use since afternoon of 8th feb.

### Log file

[Ryujinx_1.1.1164_2024-02-08_17-10-25的副本.log](https://github.com/Ryujinx/Ryujinx/files/14212705/Ryujinx_1.1.1164_2024-02-08_17-10-25.log)

### OS

macOS 12.7.3

### Ryujinx version

17.0.0.1

### Game version

1.0.0

### CPU

Apple M1

### GPU

Apple M1

### RAM

16GB

**Comment by AcK77** [comment]
You have debug log enabled, which is useless for common user and can be disabled.
Based on your log file:
```
00:01:31.951 |I| Hid Configure: Configured Controller ProController to Player2
00:01:31.951 |I| Hid Configure: Configured Controller Handheld to Handheld
00:01:31.951 |I| Hid Configure: Configured Controller JoyconPair to Player1
```
The game only ask of one player with a controller sets. So you have to disabled Player2. That's why you can't pass the controller Applet. You can come to our discord for support if needed.
Thanks.
