### ISSUE TITLE
[Bug]Raiden V Director's Cut [01002b000d97e000] freezes up nearly straight away when you load the game

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6289]
### Description of the issue

freezes up nearly straight away when you load the game

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1173_2024-02-10_16-28-42.log](https://github.com/Ryujinx/Ryujinx/files/14228631/Ryujinx_1.1.1173_2024-02-10_16-28-42.log)

### OS

Windows 10

### Ryujinx version

1.1.1173

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1640 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games

**Comment by AcK77** [comment]
Because duplicate games state issues isn't useful at all, it's just waste our time to manage issues instead of be focused on the project.
Report game specific issues is only useful and needed if a game have a regression, if not, some issues aren't still fixed since years because we can't fixes everything as a free-time project, we just doing our best.
So we prefer to get everything in the same place (the games list) and then we can try to fixes as much issues as possible to get things fixed for differents games at the same time.

**Comment by ScottNash042** [comment]
thats not true one bit
look at #6203 and #6270 and #5974 to name a few
i just checked on the games list and they haven't been updated for years so they all get forgotten
everyone needs to update their bug report regular and this isn't happening 
needs a way better system then the crap system that is happening now

**Comment by AcK77** [comment]
Everyone can update a bug report in an issue of the games list by just posting a comment.
If some games are forgotten it's because they doesn't have a huge interest from users and probably some devs too.
We do (and did) our best to get the most of games playable, that's why a bunch of them are playable day 1 on release date, but we can't get some edge cases working for some reasons (interest, free time, etc...), maybe they will be fixed one day because we fixed something in a more popular game.
If you know a better way to fix "the crap system", feel free to suggest anything that could help us, at least, help us more than duplicate issue just because you decide something is forgotten and needs more attention.

**Comment by benderscruffy** [comment]
don't get me wrong 
you devs are doing a fantastic job
it just on the game list side now that EmulationFanatic hasnt been around for a year you need more than one person looking after the list
you need to make 2 or 3 people collaborators  who are passionate and have time to do the testing 
maybe the system needs to be a bit more automated like after a month or two a message comes up saying time to update or closed the issue or something like that

**Comment by ScottNash042** [comment]
don't get me wrong
you devs are doing a fantastic job
the games list side is let down as EmulationFanatic hasnt been around for a year and shouldn't be left to one person
maybe there should be 2 or 3 collaborators who are passionate and have the time to do the testing aswell
maybe there should be an automated system that after a month or 2 a message says to please update or close the issue 
something like that to remind people

**Comment by piplup55** [comment]
> there should be 2 or 3 collaborators who are passionate and have the time to do the testing aswell maybe there should be an automated system that after a month or 2 a message says to please update or something like that to remind people

there are more than 2-3 collaborators on the game list, furthermore you can't expected a collaborator to buy over 3,000 games for one console

**Comment by benderscruffy** [comment]
well EmulationFanatic did 2606 issues
didn't he buy them all ????

**Comment by ScottNash042** [comment]
well EmulationFanatic had 2606 in the game list
didn't he buy them all ???

**Comment by riperiperi** [comment]
> the games list side is let down as EmulationFanatic hasnt been around for a year and shouldn't be left to one person
maybe there should be 2 or 3 collaborators who are passionate and have the time to do the testing aswell

We don’t control if people drop off of the face of the planet. He wasn’t on like a contract or something. This is an open source project, it’s up to the individual whether or not they want to buy and test thousands of games. I’d expect that to be an outlier case.
