### ISSUE TITLE
[Bug] Ryujinx automatically close after attempting to change the time

### ISSUE THREAD

**Issue by JustHereIam** [Ryujinx/Ryujinx#6632]
### Description of the issue

Ryujinx does not allow me to change the time.
When I try to change the time (hour and minutes), program closes/crashes.
I would like to move the time around time when play ACNH so this is quite troublesome.

### Reproduction steps

1. Opened the setting
2. At the System Time section, clicked hours and minutes part to change the time.
3. Program immediately closes/crashs.

### Log file

[Ryujinx_1.1.1268_2024-04-08_18-19-19.log](https://github.com/Ryujinx/Ryujinx/files/14911404/Ryujinx_1.1.1268_2024-04-08_18-19-19.log)

### OS

Windows 11

### Ryujinx version

1.1.1268

### Game version

Animal Crossing New Horizon 2.0.6

### CPU

2th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz

### GPU

NVDIA GeForce RTX 3050 Ti

### RAM

16.0 GB

**Comment by Kfollen93** [comment]
I can take this one.

**Comment by gdkchan** [comment]
Should I assign it to you?

**Comment by Kfollen93** [comment]
> Should I assign it to you?

Leave it open for someone else. I don't think I'll have time to go in depth regarding the date issue as well.
I may keep looking at it in the background if no one picks it up though (in which I'll comment here).

**Comment by RuinousPrincess** [comment]
I have this exact same issue myself with changing the clock just crashes the program and another odd problem where changing the date/time doesn't actually save. Instead it reverts back to the date set to my PC rather set it to whatever I want. It keeps reverting to match my PC.

**Comment by nico-abram** [comment]
I think the bug is in SettingsViewModel.cs , this line stores the difference in seconds between the current system time and the configured time
`config.System.SystemTimeOffset.Value = Convert.ToInt64((CurrentDate.ToUnixTimeSeconds() + CurrentTime.TotalSeconds) - DateTimeOffset.Now.ToUnixTimeSeconds());`
That in and of itself sounds fine to me, when we go backwards in time it results in a large negative number
Then it loads that value here
```cs
            DateTime currentDateTime = DateTime.Now;

            CurrentDate = currentDateTime.Date;
            CurrentTime = currentDateTime.TimeOfDay.Add(TimeSpan.FromSeconds(config.System.SystemTimeOffset));
```
Now here's the problem AIUI
The date is always set to the current system time date, and then the time gets the entirety of the offset. This can result in a hilariously large negative time-within-the-day that crashes Avalonia's datetime picker

I think the fix is just checking if the absolute value of the offset is larger than a day when loading, if so substract from the CurrentDate instead, and use the remainder on the currentTime?
