### ISSUE TITLE
[Bug] Minor UI issue + [Feature Request]

### ISSUE THREAD

**Issue by floppyD** [Ryujinx/Ryujinx#6684]
### Description of the issue

It's hard to resize the window when it's active.

Also a suggestion, an option to set default window size to multiples of 720p. Like 1x, 2x, 3x and so on.

### Reproduction steps

[output.webm](https://github.com/Ryujinx/Ryujinx/assets/29208110/90768779-9c79-422f-9dee-00f4627b391b)

### Log file

.

### OS

Windows 10

### Ryujinx version

1.1.1283

### Additional context?

The only way to get proper 720p in windowed mode (without painfully resizing manually) is by editing Config.json and using

``"window_size_width": 1280,
"window_size_height": 777``

**Comment by CatMow** [comment]
yes!!! same issue!!

when i updated to the new ui it did this. resizing is possible but is hard

**Comment by SylveonDeko** [comment]
Was there a version where this worked before? That included the new ui?

**Comment by SylveonDeko** [comment]
Gonna take on the window resize, have a potentially working fix

**Comment by github-1348A55** [comment]
I don't know if this has anything to do with it,
When I try to operate the upper menu, I can't see the cursor, which is inconvenient.
You can select it just because you can't see it, but you have to click it while looking for the judgment.
The bottom docking, aspect ratio, and bottom volume items are fine.

**Comment by gdkchan** [comment]
Bug has been fixed on #6725, feature request should have been created as a separate issue.
