### ISSUE TITLE
[Feature Request] Configurable texture cache total size limit

### ISSUE THREAD

**Issue by jasondyoungberg** [Ryujinx/Ryujinx#6798]
### Overview

Add a way to increase [MaxTextureSizeCapacity](https://github.com/Ryujinx/Ryujinx/blob/a23d8cb92f3f1bb8dc144f4d9fb3fddee749feae/src/Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs#L49) in settings to allow for mods with high resolution textures.

### Smaller details

This could be similar to the extended memory option.

### Nature of request

New option in settings.

### Why would this feature be useful?

When playing totk with [the optimizer](https://github.com/MaxLastBreath/TOTK-mods) on high settings, my game will crash after around one hour. Increasing the texture cache to 1536 MiB fixes this.

**Comment by piplup55** [comment]
i don't think this is a good idea, it doesn't solve the main reason for the crash, it would be better to fix the issue then adding a new option that will confuse more users

**Comment by jasondyoungberg** [comment]
What is the main issue? I was under the impression that this was due to the size of the texture cache?

**Comment by gdkchan** [comment]
Adding settings is not a good way to solve this kind of issue, since people will not change said settings and still get the problem regardless, and then ask us why the problem is happening. Also games crashing when the size limit is "too low" is not expected behaviour, it is a bug, probably related to the texture flush. It would be good if someone could find the conditions to make it happen so that we can reproduce and fix it, although if it only happens after 1 hour playing the game, it doesn't sound easy to reproduce. Maybe there is a way to trigger it quickly by artificially causing several textures to flush, although I have tried that in the past (with a different game) and was not able to cause it to crash.

**Comment by jasondyoungberg** [comment]
Alright thanks, I'll see if I can find a consistent way to replicate the crash, didn't realize there was a separate issue here
