### ISSUE TITLE
[Bug] Cannot use bundled updates (crash)

### ISSUE THREAD

**Issue by Foul-Tarnished** [Ryujinx/Ryujinx#7074]
### Description of the issue

When I try to boot Fire Emblem Three Houses with the 1.2.0 update bundled into it (with yanu tool) it just crash
This was not happening a few months earlier.

I realized now ryujinx see these bundled updates in the manage updates menu, and it wasn't selected, so it was booting with 1.0.0 and I had to manually select that bundled update (weird behavior ngl) for ryu to use it, but then it crash

Before, it would _always_ load the bundled 1.2.0 (the manage updates menu would not see anything), now you have to select it, and it crash
booting 1.0.0 work fine though

### Reproduction steps

use yanu tool to merge update 1.2.0 into FE3H.xci
select the bundled 1.2.0 update inside ryujinx manage update menu
boot the game, it crash

### Log file

[Ryujinx_1.1.1354_2024-07-20_19-13-20.log](https://github.com/user-attachments/files/16321788/Ryujinx_1.1.1354_2024-07-20_19-13-20.log)

### OS

Windows 11 23H2

### Ryujinx version

1.1.1354

### Game version

1.2.0

### CPU

7800X3D

### GPU

RTX 4080

### RAM

32GB

### List of applied mods

60FPS mod (exefs for 1.2.0)
no outline mod (romfs)

### Additional context?

I think the PR that added support for multi-xci might be the culprit

**Comment by Foul-Tarnished** [comment]
I have super mario 3d world + bowser fury with 1.1.0 bundled, and it seems to work ?
I don't get it

**Comment by redomCL** [comment]
yes,v1.1.1350-1.1.1.361 has this bug.

v1.1.1349 has not this issues.

maybe Add support for multi game XCIs (second try) #6515

**Comment by TSRBerry** [comment]
I don't see an issue here, the log in the issue description says there is a missing title key and there isn't really anything I can do about that.
Since this issue only seems to happen with manually merged files I'm assuming they just aren't valid.

Should this happen with actual XCIs with bundled updates, then that's a different story and we should reopen this issue.
But I'd like to have a log for that, since I wouldn't be able to fix that without one.
