### ISSUE TITLE
Reintroduce Apple hypervisor force ordered memory change

### ISSUE THREAD

**Issue by stonerl** [Ryujinx/Ryujinx#7106]
### Overview

I was skimming through closed and open PRs and stumbled over #6068 and #6585.

From what I understand, is that changes in  #6068 (Revert Apple hypervisor force ordered memory change) were made because some people were apparently experiencing freezes.

In PR #6068 I found a linked patch: https://github.com/blackxfiied/Ryujinx/commit/1972eb26f1f687082bba8e81ed49417bdf244e2e

I applied this patch on top of the current master branch 95d252b7b8d9940be032e6f4e37fba37b2fb9aad and was able to play, e.g., BOTW with the hypervisor enabled.

So I wondered whether these freezes were really the result of the now reverted changes to the hypervisor.

### Smaller details

Since I don't own that many games, I was only able to test with the following with hypervisor enabled:

- The Legend of Zelda: BOTW
- The Legend of Zelda: TOTK
- The Legend of Zelda: Link's Awakening
- Metroid Prime Remastered
- MK8D

In total, it tested all games for about 5 hours, and did not experience any freeze. But I will continue testing and report any freezes that may happen!

### Nature of request

Add this patch: https://github.com/blackxfiied/Ryujinx/commit/1972eb26f1f687082bba8e81ed49417bdf244e2e

### Why would this feature be useful?

In my limited testing, this makes games perform better.

**Comment by riperiperi** [comment]
You should read the actual PR message for https://github.com/Ryujinx/Ryujinx/pull/6068. While https://github.com/Ryujinx/Ryujinx/pull/5898 did allow BOTW to run for some time, it made other games freeze very often, like the newer Pokemon games. Without identifying why that is the case, it isn't going to be reintroduced.

**Comment by stonerl** [comment]
I did read the PR message. The reason for that PR was: _“I'm not sure if that was caused by this change as those games already had problems on hypervisor before that change (AFAIK?), but they do seem to happen much more frequently now.”_ 

But to me, this seems to be a problem with the hypervisor, and certain games, in general and not that patch in particular (from my limited testing).

I bought Pokémon Violet today, to give it a test, since it was one of the games in question.

With the patch, I got to the title screen without freezes. Then the game froze.

With the latest version available for download (1.1.1359) I was able to select the language and got to the character selection screen. When I wanted to change the hairstyle, the game froze.

So with that in mind, I could conclude the patch got me further into the game before freezing, but basically that game does not run reliably when the hypervisor was enabled. Therefore, I would hypothesize that it is not the patch that is causing issues.

Having it in the code again and disabling the hypervisor by default as suggested in PR #6585, maybe with a warning/note telling the user that some games might freeze with hypervisor enabled, would be more beneficial, IMHO.

**Comment by jcm93** [comment]
There were definitely other changes made, likely around the time of #5898 but that were not #5898, that made the hypervisor more predisposed to freezing in some titles, but I do not think anyone has done the specific work/bisecting required to isolate them, much less figure out the root cause. You can test this by running certain games (my test case was usually Red Dead Redemption) under the hypervisor from old builds (e.g. contemporary to that game's release) compared to now.

The situation is further complexified by the fact that different Mac hardware is variously predisposed to this hypervisor freezing. The base M1 will freeze much less often than the M1 Max, for example, in my testing. Thus, testing for these 'regressions' is likely to be somewhat time consuming.

Rather than reintroduce this patch, I think the more valuable route of investigation might be isolating what caused the hypervisor to become more unstable in general around that time.

**Comment by stonerl** [comment]
How could I help with testing here? Can you pinpoint me to a specific commit where I could start investigation?

**Comment by stonerl** [comment]
Found the offending addition, it is PR #5887. Starting with that PR, RDR1 freezes within 5 minutes.

**Comment by stonerl** [comment]
I'm going to close this one. Since, as the devs have pointed out, there is a deeper underlying problem that needs to addressed.
