### ISSUE TITLE
[Bug] It may fill the root partition with crap and then close

### ISSUE THREAD

**Issue by totolgueimer** [Ryujinx/Ryujinx#7361]
### Description of the issue

https://github.com/user-attachments/assets/5a39fe9d-1b40-4288-b85f-c3d0b5e66712

It was working fine until it updated and now it crashes, reverting to an old version doesnt fix the problem

### Reproduction steps

Just open a game

### Log file

It doesnt generate any log file for some reason

### OS

Arch Linux

### Ryujinx version

1.1.1398

### Game version

13.0.2

### CPU

AMD Ryzen 7 PRO 3700u

### GPU

AMD Radeon Vega 10 Graphics

### RAM

16GB

**Comment by MetrosexualGarbodor** [comment]
Without a log it's impossible to know why it crashed, but there's a strong likelihood that your RAM is full, it defaulted to swap, filled your storage and crashed because of insufficient RAM to run the game. Either make storage space or close other programs.

In the future, please don't disable logging and use Discord for general support instead of opening issues.
