### ISSUE TITLE
Ryujinx not letting me boot up game 

### ISSUE THREAD

**Issue by MazinCaizar** [Ryujinx/Ryujinx#835]
![Capture](https://user-images.githubusercontent.com/58243441/69694572-1e6bc080-108e-11ea-90db-35035b1d1871.PNG)

**Comment by AcK77** [comment]
Thanks for your report. This seems like an audio backend issue as the log said, libsoundio doesn’t support your device, you should use OpenAL instead. For support on issues like these, it's best to post a log and contact us on our Discord for assistance.

Because of this, we'll close it unless you can provide us some more information! Feel free to ask for help in our support channel on our Discord server.

Thanks.
