### ISSUE TITLE
CPU JIT cache disposal

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx#885]
Currently the main problem of the JIT cache is that functions are never removed from the cache. #740 improves that a bit, by removing functions that are no longer used from the cache, but we need to also support cache disposal. When the emulation is ended, all the memory used for the code should be freed, and this is not happening currently. ~~Right now it's not a big deal because ending emulation and starting a new game is not possible, but it will be once this is supported.~~ (This is already supported today).

We may want to consider having one JitCache per Translator instance (JitCache is currently static and thus shared).

**Comment by emmauss** [comment]
> We may want to consider having one JitCache per Translator instance (JitCache is currently static and thus shared).
this would be needed for the disassembler, for ondemand translation.

**Comment by FICTURE7** [comment]
An approach to solve this might be to leverage the GC. We can use finalizers to call our "Free" function. This should save us from having to write the graph traversal code and such to figure out which TranslatedFunction is live.

I was thinking something like this:
```csharp
class TranslatedFunction : IDisposable {
  readonly IntPtr _ptr;
  readonly IAllocator _allocator;
  readonly Set<TranslatedFunction> _children;

  ~TranslatedFunction() =>
    _allocator.Free(_ptr);
}

// -or-

class TranslatedFunction : IDisposable {
  readonly IJitMemoryBlock _block;
  readonly Set<TranslatedFunction> _children;

  ~TranslatedFunction() =>
    _block.Dispose(); // Should not be needed if _block already does the finalization stuff.
}

var f0 = new TranslatedFunction();
var f1 = new TranslatedFunction();
var f2 = new TranslatedFunction();

f0._children.Add(f1);
f1._children.Add(f2);

// f0  ;; root
//  `- f1
//      `-f2

f0 = null;

// x ~f0~  ;; root ref is dead, gets free'd with children.
//  `- f1
//      `-f2
```
The problem with this might be order of finalization which is non-deterministic. But if the root function is not reachable, the children should not be reachable as well. I am also not sure how well this will play with the dynamic table, I believe we have to ensure that we do not free HCQ code, otherwise the dynamic table could point to free'd memory. (Unless add a more book keeping)

**Comment by gdkchan** [comment]
I guess for that to work, we'd also need to ensure that the function being removed is not currently running. The object having no references doesn't mean that the function is not currently being executed. I guess this issue can be avoided if we ensure that all functions running have a live reference to the TranslatedFunction object.

**Comment by FICTURE7** [comment]
Oof right. This is going to be tricky to get right.

**Comment by EmulationFanatic** [comment]
Closed by https://github.com/Ryujinx/Ryujinx/pull/1518
