### ISSUE TITLE
Add support for nro files with romfs

### ISSUE THREAD

**Issue by TurtleP** [Ryujinx/Ryujinx#94]
Currently Ryujinx cannot access romfs from an nro that has one.
Works on hardware, and attached is my application that does this.

[LovePotion.zip](https://github.com/gdkchan/Ryujinx/files/1933354/LovePotion.zip)

While I can call `romfsInit`, it just doesn't return the right code (which would be 0).
From there I change to the romfs directory to run the game's files.

Not sure if those details are helpful, but if you need them, there they are 😄

**Comment by AcK77** [comment]
It's probably related to the way the RomFS is found (by get the NRO path).
I need the return value of the `romfsInit` to know where is the problem...
Thanks.

(https://github.com/switchbrew/libnx/blob/d3cc781bf625e5e09ccc5bceb3e2fc790328d299/nx/source/runtime/devices/romfs_dev.c#L163 as remember)

**Comment by tommai78101** [comment]
You can test to see the return value of the `romfsInit`. Follow the instructions in the provided NRO build, and you'll be able to see the results.

In my case, the result is 0xA.

[romfsInit.zip](https://github.com/gdkchan/Ryujinx/files/1934192/romfsInit.zip)

If the result is bad, it means it did receive a `romfs` handle.
If the result is good, it means it did not receive a `romfs` handle.

Why it's bad instead of good? I based the code off from the official repository here:

https://github.com/switchbrew/switch-examples/blob/master/fs/romfs/source/main.c#L36-L45

**Comment by tommai78101** [comment]
Oh, scratch that, it's a bug.  Commit was just pushed.

https://github.com/switchbrew/switch-examples/commit/0ff790f032

**Comment by tommai78101** [comment]
[fixed_romfsInit.zip (includes updated source code)](https://github.com/gdkchan/Ryujinx/files/1934207/fixed_romfsInit.zip)

So, you should be able to read the values at any time.

**Comment by tommai78101** [comment]
@AcK77 Found out why it's returning 0x0000000A:

https://github.com/switchbrew/libnx/blob/master/nx/source/runtime/devices/romfs_dev.c#L256

**Comment by tommai78101** [comment]
Ok, so quick update on this:

If romfsInit() succeeds, you would get this number returned: 83831218, or 0x04FF29B2.

**Comment by TurtleP** [comment]
@tommai78101 a successful `romfsInit()` returns 0, failure is pretty much anything else.

**Comment by gdkchan** [comment]
Should be fixed with c2c765b30fdfa9184df580133e22ae946eebc022.
